@startuml
skinparam backgroundColor white
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName Times New Roman
skinparam defaultFontSize 18
skinparam dpi 180
skinparam classAttributeIconSize 0
skinparam roundcorner 0
skinparam packageStyle rectangle
skinparam classBackgroundColor white
skinparam usecaseBackgroundColor white
skinparam nodesep 75
skinparam ranksep 85
skinparam ArrowFontSize 15
skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true
hide circle
hide empty members

top to bottom direction
class NhomSanPham <<hệ thống ngoài>> {
MaNhom : String
TenNhom : String
}
class SanPham <<hệ thống ngoài>> {
MaSP : String
TenSP : String
NhaSanXuat : String
GiaHienHanh : Decimal
ConHang : Boolean
MoTa : String
ThongSo : String
}
class HinhAnhSanPham <<hệ thống ngoài>> {
ThuTu : Integer
DuongDan : String
}
class GioHang <<phiên>> {
/TienHang : Decimal
}
class ChiTietGioHang {
SoLuong : Integer
DonGia : Decimal
/ThanhTien : Decimal
}
NhomSanPham "1" -right- "0..*" SanPham
SanPham "1" *-right- "0..*" HinhAnhSanPham
GioHang "1" *-right- "0..*" ChiTietGioHang
ChiTietGioHang "0..*" -up-> "1" SanPham : chọn
note bottom of GioHang : Giỏ tồn tại trong một phiên truy cập.

@enduml