@startuml
skinparam backgroundColor white
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName Times New Roman
skinparam defaultFontSize 18
skinparam dpi 180
skinparam classAttributeIconSize 0
skinparam roundcorner 0
skinparam packageStyle rectangle
skinparam classBackgroundColor white
skinparam usecaseBackgroundColor white
skinparam nodesep 75
skinparam ranksep 85
skinparam ArrowFontSize 15
skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true
hide circle
hide empty members

top to bottom direction
entity KhachHang {
 {field} *MaKH : int <<PK>>
 {field} TenDangNhap <<UQ>>
 {field} HoTen
 {field} NgaySinh
 {field} GiayTo
 {field} DiaChi
 {field} DienThoai
 {field} MatKhauHash
 {field} Salt
 {field} Email
}
entity PhiGiaoHang {
 {field} *KhuVuc : varchar(20) <<PK>>
 {field} *LoaiGiao : varchar(20) <<PK>>
 {field} PhiCoBan : decimal(18,0)
}
entity DonHang {
 {field} *MaDH : int <<PK>>
 {field} MaYeuCau <<UQ>>
 {field} MaKH <<FK>>
 {field} KhuVucGiao, LoaiGiao <<FK ghép>>
 {field} TenNguoiMua
 {field} EmailNguoiMua
 {field} TenNguoiNhan
 {field} DiaChiNhan
 {field} DienThoaiNhan
 {field} TienHang
 {field} PhiGiao
 {field} PhiThe
 {field} TongTien
 {field} ThoiDiem
}
entity ChiTietDonHang {
 {field} *MaDH : int <<PK,FK>>
 {field} *MaSP : varchar(20) <<PK>>
 {field} TenSP
 {field} SoLuong
 {field} DonGia
 {field} ThanhTien
}
entity ThanhToan {
 {field} *MaDH : int <<PK,FK>>
 {field} LoaiThe
 {field} BonSoCuoi
 {field} MaGiaoDich <<UQ>>
 {field} SoTien
 {field} ThoiDiem
}
entity EmailXacNhan {
 {field} *MaDH : int <<PK,FK>>
 {field} DiaChiEmail
 {field} NoiDung
 {field} TrangThai
 {field} ThoiDiem
}
KhachHang ||--o{ DonHang
PhiGiaoHang ||--o{ DonHang
DonHang ||--|{ ChiTietDonHang
DonHang ||--|| ThanhToan
DonHang ||--o| EmailXacNhan
note bottom of ChiTietDonHang
MaSP tham chiếu catalog.SanPham.
Không ép FK qua hệ thống ngoài.
end note

@enduml
