@startuml
skinparam backgroundColor white
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName Times New Roman
skinparam defaultFontSize 18
skinparam dpi 180
skinparam classAttributeIconSize 0
skinparam roundcorner 0
skinparam packageStyle rectangle
skinparam classBackgroundColor white
skinparam usecaseBackgroundColor white
skinparam nodesep 75
skinparam ranksep 85
skinparam ArrowFontSize 15
skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true
hide circle
hide empty members

top to bottom direction
entity "catalog.NhomSanPham" as N {
 {field} *MaNhom : varchar(20) <<PK>>
 {field} TenNhom : nvarchar(100)
}
entity "catalog.SanPham" as S {
 {field} *MaSP : varchar(20) <<PK>>
 {field} MaNhom : varchar(20) <<FK>>
 {field} TenSP : nvarchar(150)
 {field} NhaSanXuat : nvarchar(100)
 {field} MoTa, ThongSo : nvarchar(1000)
 {field} GiaHienHanh : decimal(18,0)
 {field} ConHang : bit
}
entity "catalog.HinhAnhSanPham" as H {
 {field} *MaSP : varchar(20) <<PK,FK>>
 {field} *ThuTu : int <<PK>>
 {field} DuongDan : nvarchar(300)
}
N ||--o{ S
S ||--o{ H

@enduml
