@startuml
skinparam backgroundColor white
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName Times New Roman
skinparam defaultFontSize 18
skinparam dpi 180
skinparam classAttributeIconSize 0
skinparam roundcorner 0
skinparam packageStyle rectangle
skinparam classBackgroundColor white
skinparam usecaseBackgroundColor white
skinparam nodesep 75
skinparam ranksep 85
skinparam ArrowFontSize 15
skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true
hide circle
hide empty members

left to right direction
usecase "UC05 Đặt hàng" as O
usecase "UC04 Đăng nhập" as A
usecase "UC06 Nhập thông tin\nngười nhận" as N
usecase "Chọn loại giao hàng" as G
usecase "UC07 Tính chi phí" as F
usecase "UC08 Thanh toán" as P
usecase "Kiểm tra thẻ qua\ndịch vụ thanh toán" as V
usecase "UC09 Ghi nhận đơn" as S
usecase "UC10 Gửi email\nxác nhận" as M
O ..> A : <<include>>
O ..> N : <<include>>
O ..> G : <<include>>
G ..> F : <<include>>
O ..> P : <<include>>
P ..> V : <<include>>
O ..> S : <<include>>
M ..> S : <<extend>>\n[có email]
A -[hidden]down-> N
N -[hidden]down-> G
G -[hidden]down-> P
P -[hidden]down-> S

@enduml