@startuml
skinparam backgroundColor white
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName Times New Roman
skinparam defaultFontSize 18
skinparam dpi 180
skinparam classAttributeIconSize 0
skinparam roundcorner 0
skinparam packageStyle rectangle
skinparam classBackgroundColor white
skinparam usecaseBackgroundColor white
skinparam nodesep 75
skinparam ranksep 85
skinparam ArrowFontSize 15
skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true
hide circle
hide empty members

top to bottom direction
actor "Khách truy cập" as Guest
actor "Khách hàng" as Customer
rectangle "Hệ thống e-SHOPPING" {
 usecase "UC01\nXem sản phẩm" as P
 usecase "UC02\nQuản lý giỏ hàng" as C
 usecase "UC03\nĐăng ký tài khoản" as R
 usecase "UC04\nĐăng nhập" as L
 usecase "UC05\nĐặt hàng" as O
 P -[hidden]down-> C
 C -[hidden]down-> R
 R -[hidden]down-> L
 L -[hidden]down-> O
 O ..> L : <<include>>
}
actor "Hệ thống quản lý\nsản phẩm" as Catalog
actor "Dịch vụ thanh toán\ntrực tuyến" as Pay
actor "Dịch vụ email" as Email
Guest -- P
Guest -- C
Guest -- R
Customer -up-|> Guest
Customer -- L
Customer -- O
P -- Catalog
O -- Pay
O -- Email
Catalog -[hidden]down-> Pay
Pay -[hidden]down-> Email

@enduml