namespace QuanLyCuaHangOnline
{
    partial class FrmCheckout
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.lblNguoiMua = new System.Windows.Forms.Label();
            this.lblNguoiMua.Name = "lblNguoiMua";
            this.lblNguoiMua.Location = new System.Drawing.Point(25, 25);
            this.lblNguoiMua.Size = new System.Drawing.Size(680, 26);
            this.lblNguoiMua.Text = "";
            this.Controls.Add(this.lblNguoiMua);
            this.lblHoTen = new System.Windows.Forms.Label();
            this.lblHoTen.Name = "lblHoTen";
            this.lblHoTen.Location = new System.Drawing.Point(25, 80);
            this.lblHoTen.Size = new System.Drawing.Size(155, 26);
            this.lblHoTen.Text = "Họ tên người nhận";
            this.Controls.Add(this.lblHoTen);
            this.txtHoTen = new System.Windows.Forms.TextBox();
            this.txtHoTen.Name = "txtHoTen";
            this.txtHoTen.Location = new System.Drawing.Point(190, 75);
            this.txtHoTen.Size = new System.Drawing.Size(520, 27);
            this.Controls.Add(this.txtHoTen);
            this.lblDiaChi = new System.Windows.Forms.Label();
            this.lblDiaChi.Name = "lblDiaChi";
            this.lblDiaChi.Location = new System.Drawing.Point(25, 132);
            this.lblDiaChi.Size = new System.Drawing.Size(155, 26);
            this.lblDiaChi.Text = "Địa chỉ nhận";
            this.Controls.Add(this.lblDiaChi);
            this.txtDiaChi = new System.Windows.Forms.TextBox();
            this.txtDiaChi.Name = "txtDiaChi";
            this.txtDiaChi.Location = new System.Drawing.Point(190, 127);
            this.txtDiaChi.Size = new System.Drawing.Size(520, 27);
            this.Controls.Add(this.txtDiaChi);
            this.lblDienThoai = new System.Windows.Forms.Label();
            this.lblDienThoai.Name = "lblDienThoai";
            this.lblDienThoai.Location = new System.Drawing.Point(25, 184);
            this.lblDienThoai.Size = new System.Drawing.Size(155, 26);
            this.lblDienThoai.Text = "Điện thoại";
            this.Controls.Add(this.lblDienThoai);
            this.txtDienThoai = new System.Windows.Forms.TextBox();
            this.txtDienThoai.Name = "txtDienThoai";
            this.txtDienThoai.Location = new System.Drawing.Point(190, 179);
            this.txtDienThoai.Size = new System.Drawing.Size(520, 27);
            this.Controls.Add(this.txtDienThoai);
            this.lblGiao = new System.Windows.Forms.Label();
            this.lblGiao.Name = "lblGiao";
            this.lblGiao.Location = new System.Drawing.Point(25, 243);
            this.lblGiao.Size = new System.Drawing.Size(650, 26);
            this.lblGiao.Text = "Hình thức giao hàng";
            this.Controls.Add(this.lblGiao);
            this.lblKhuVuc = new System.Windows.Forms.Label();
            this.lblKhuVuc.Name = "lblKhuVuc";
            this.lblKhuVuc.Location = new System.Drawing.Point(25, 288);
            this.lblKhuVuc.Size = new System.Drawing.Size(100, 26);
            this.lblKhuVuc.Text = "Khu vực";
            this.Controls.Add(this.lblKhuVuc);
            this.cboKhuVuc = new System.Windows.Forms.ComboBox();
            this.cboKhuVuc.Name = "cboKhuVuc";
            this.cboKhuVuc.Location = new System.Drawing.Point(125, 282);
            this.cboKhuVuc.Size = new System.Drawing.Size(205, 28);
            this.cboKhuVuc.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboKhuVuc.Items.AddRange(new object[] { "Nội thành", "Ngoại thành", "Tỉnh khác" });
            this.cboKhuVuc.SelectedIndex = 0;
            this.Controls.Add(this.cboKhuVuc);
            this.lblLoaiGiao = new System.Windows.Forms.Label();
            this.lblLoaiGiao.Name = "lblLoaiGiao";
            this.lblLoaiGiao.Location = new System.Drawing.Point(370, 288);
            this.lblLoaiGiao.Size = new System.Drawing.Size(110, 26);
            this.lblLoaiGiao.Text = "Loại giao";
            this.Controls.Add(this.lblLoaiGiao);
            this.cboLoaiGiao = new System.Windows.Forms.ComboBox();
            this.cboLoaiGiao.Name = "cboLoaiGiao";
            this.cboLoaiGiao.Location = new System.Drawing.Point(480, 282);
            this.cboLoaiGiao.Size = new System.Drawing.Size(230, 28);
            this.cboLoaiGiao.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboLoaiGiao.Items.AddRange(new object[] { "Thường", "Nhanh", "Trong ngày" });
            this.cboLoaiGiao.SelectedIndex = 0;
            this.Controls.Add(this.cboLoaiGiao);
            this.lblTienHang = new System.Windows.Forms.Label();
            this.lblTienHang.Name = "lblTienHang";
            this.lblTienHang.Location = new System.Drawing.Point(375, 337);
            this.lblTienHang.Size = new System.Drawing.Size(335, 26);
            this.lblTienHang.Text = "";
            this.Controls.Add(this.lblTienHang);
            this.lblPhiGiao = new System.Windows.Forms.Label();
            this.lblPhiGiao.Name = "lblPhiGiao";
            this.lblPhiGiao.Location = new System.Drawing.Point(375, 375);
            this.lblPhiGiao.Size = new System.Drawing.Size(335, 26);
            this.lblPhiGiao.Text = "";
            this.Controls.Add(this.lblPhiGiao);
            this.lblTongTien = new System.Windows.Forms.Label();
            this.lblTongTien.Name = "lblTongTien";
            this.lblTongTien.Location = new System.Drawing.Point(375, 413);
            this.lblTongTien.Size = new System.Drawing.Size(335, 26);
            this.lblTongTien.Text = "";
            this.Controls.Add(this.lblTongTien);
            this.btnThanhToan = new System.Windows.Forms.Button();
            this.btnThanhToan.Name = "btnThanhToan";
            this.btnThanhToan.Location = new System.Drawing.Point(480, 462);
            this.btnThanhToan.Size = new System.Drawing.Size(230, 36);
            this.btnThanhToan.Text = "Tiếp tục thanh toán";
            this.btnThanhToan.UseVisualStyleBackColor = true;
            this.btnThanhToan.Click += this.btnThanhToan_Click;
            this.Controls.Add(this.btnThanhToan);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(740, 520);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Name = "FrmCheckout";
            this.Text = "Checkout - Người nhận và giao hàng";
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        private System.Windows.Forms.Label lblNguoiMua;
        private System.Windows.Forms.Label lblHoTen;
        private System.Windows.Forms.TextBox txtHoTen;
        private System.Windows.Forms.Label lblDiaChi;
        private System.Windows.Forms.TextBox txtDiaChi;
        private System.Windows.Forms.Label lblDienThoai;
        private System.Windows.Forms.TextBox txtDienThoai;
        private System.Windows.Forms.Label lblGiao;
        private System.Windows.Forms.Label lblKhuVuc;
        private System.Windows.Forms.ComboBox cboKhuVuc;
        private System.Windows.Forms.Label lblLoaiGiao;
        private System.Windows.Forms.ComboBox cboLoaiGiao;
        private System.Windows.Forms.Label lblTienHang;
        private System.Windows.Forms.Label lblPhiGiao;
        private System.Windows.Forms.Label lblTongTien;
        private System.Windows.Forms.Button btnThanhToan;
    }
}
