namespace QuanLyCuaHangOnline
{
    partial class FrmChiTietSanPham
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.lblMaSP = new System.Windows.Forms.Label();
            this.lblMaSP.Name = "lblMaSP";
            this.lblMaSP.Location = new System.Drawing.Point(20, 27);
            this.lblMaSP.Size = new System.Drawing.Size(140, 26);
            this.lblMaSP.Text = "Mã SP";
            this.Controls.Add(this.lblMaSP);
            this.txtMaSP = new System.Windows.Forms.TextBox();
            this.txtMaSP.Name = "txtMaSP";
            this.txtMaSP.Location = new System.Drawing.Point(165, 23);
            this.txtMaSP.Size = new System.Drawing.Size(410, 27);
            this.txtMaSP.ReadOnly = true;
            this.Controls.Add(this.txtMaSP);
            this.lblTenSP = new System.Windows.Forms.Label();
            this.lblTenSP.Name = "lblTenSP";
            this.lblTenSP.Location = new System.Drawing.Point(20, 74);
            this.lblTenSP.Size = new System.Drawing.Size(140, 26);
            this.lblTenSP.Text = "Tên sản phẩm";
            this.Controls.Add(this.lblTenSP);
            this.txtTenSP = new System.Windows.Forms.TextBox();
            this.txtTenSP.Name = "txtTenSP";
            this.txtTenSP.Location = new System.Drawing.Point(165, 70);
            this.txtTenSP.Size = new System.Drawing.Size(410, 27);
            this.txtTenSP.ReadOnly = true;
            this.Controls.Add(this.txtTenSP);
            this.lblNhom = new System.Windows.Forms.Label();
            this.lblNhom.Name = "lblNhom";
            this.lblNhom.Location = new System.Drawing.Point(20, 121);
            this.lblNhom.Size = new System.Drawing.Size(140, 26);
            this.lblNhom.Text = "Nhóm";
            this.Controls.Add(this.lblNhom);
            this.txtNhom = new System.Windows.Forms.TextBox();
            this.txtNhom.Name = "txtNhom";
            this.txtNhom.Location = new System.Drawing.Point(165, 117);
            this.txtNhom.Size = new System.Drawing.Size(410, 27);
            this.txtNhom.ReadOnly = true;
            this.Controls.Add(this.txtNhom);
            this.lblNSX = new System.Windows.Forms.Label();
            this.lblNSX.Name = "lblNSX";
            this.lblNSX.Location = new System.Drawing.Point(20, 168);
            this.lblNSX.Size = new System.Drawing.Size(140, 26);
            this.lblNSX.Text = "Nhà sản xuất";
            this.Controls.Add(this.lblNSX);
            this.txtNSX = new System.Windows.Forms.TextBox();
            this.txtNSX.Name = "txtNSX";
            this.txtNSX.Location = new System.Drawing.Point(165, 164);
            this.txtNSX.Size = new System.Drawing.Size(410, 27);
            this.txtNSX.ReadOnly = true;
            this.Controls.Add(this.txtNSX);
            this.lblGia = new System.Windows.Forms.Label();
            this.lblGia.Name = "lblGia";
            this.lblGia.Location = new System.Drawing.Point(20, 215);
            this.lblGia.Size = new System.Drawing.Size(140, 26);
            this.lblGia.Text = "Giá bán (đ)";
            this.Controls.Add(this.lblGia);
            this.txtGia = new System.Windows.Forms.TextBox();
            this.txtGia.Name = "txtGia";
            this.txtGia.Location = new System.Drawing.Point(165, 211);
            this.txtGia.Size = new System.Drawing.Size(410, 27);
            this.txtGia.ReadOnly = true;
            this.Controls.Add(this.txtGia);
            this.lblTinhTrang = new System.Windows.Forms.Label();
            this.lblTinhTrang.Name = "lblTinhTrang";
            this.lblTinhTrang.Location = new System.Drawing.Point(20, 262);
            this.lblTinhTrang.Size = new System.Drawing.Size(140, 26);
            this.lblTinhTrang.Text = "Tình trạng";
            this.Controls.Add(this.lblTinhTrang);
            this.txtTinhTrang = new System.Windows.Forms.TextBox();
            this.txtTinhTrang.Name = "txtTinhTrang";
            this.txtTinhTrang.Location = new System.Drawing.Point(165, 258);
            this.txtTinhTrang.Size = new System.Drawing.Size(410, 27);
            this.txtTinhTrang.ReadOnly = true;
            this.Controls.Add(this.txtTinhTrang);
            this.lblMoTa = new System.Windows.Forms.Label();
            this.lblMoTa.Name = "lblMoTa";
            this.lblMoTa.Location = new System.Drawing.Point(20, 314);
            this.lblMoTa.Size = new System.Drawing.Size(140, 26);
            this.lblMoTa.Text = "Mô tả";
            this.Controls.Add(this.lblMoTa);
            this.txtMoTa = new System.Windows.Forms.TextBox();
            this.txtMoTa.Name = "txtMoTa";
            this.txtMoTa.Location = new System.Drawing.Point(165, 310);
            this.txtMoTa.Size = new System.Drawing.Size(410, 95);
            this.txtMoTa.ReadOnly = true;
            this.txtMoTa.Multiline = true;
            this.txtMoTa.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.Controls.Add(this.txtMoTa);
            this.lblThongSo = new System.Windows.Forms.Label();
            this.lblThongSo.Name = "lblThongSo";
            this.lblThongSo.Location = new System.Drawing.Point(20, 429);
            this.lblThongSo.Size = new System.Drawing.Size(140, 26);
            this.lblThongSo.Text = "Thông số kỹ thuật";
            this.Controls.Add(this.lblThongSo);
            this.txtThongSo = new System.Windows.Forms.TextBox();
            this.txtThongSo.Name = "txtThongSo";
            this.txtThongSo.Location = new System.Drawing.Point(165, 425);
            this.txtThongSo.Size = new System.Drawing.Size(410, 95);
            this.txtThongSo.ReadOnly = true;
            this.txtThongSo.Multiline = true;
            this.txtThongSo.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.Controls.Add(this.txtThongSo);
            this.picSanPham = new System.Windows.Forms.PictureBox();
            this.picSanPham.Name = "picSanPham";
            this.picSanPham.Location = new System.Drawing.Point(610, 24);
            this.picSanPham.Size = new System.Drawing.Size(285, 375);
            this.picSanPham.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.picSanPham.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.Controls.Add(this.picSanPham);
            this.cboHinhAnh = new System.Windows.Forms.ComboBox();
            this.cboHinhAnh.Name = "cboHinhAnh";
            this.cboHinhAnh.Location = new System.Drawing.Point(610, 420);
            this.cboHinhAnh.Size = new System.Drawing.Size(285, 28);
            this.cboHinhAnh.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.Controls.Add(this.cboHinhAnh);
            this.lblSL = new System.Windows.Forms.Label();
            this.lblSL.Name = "lblSL";
            this.lblSL.Location = new System.Drawing.Point(20, 567);
            this.lblSL.Size = new System.Drawing.Size(120, 26);
            this.lblSL.Text = "Số lượng";
            this.Controls.Add(this.lblSL);
            this.nudSoLuong = new System.Windows.Forms.NumericUpDown();
            this.nudSoLuong.Name = "nudSoLuong";
            this.nudSoLuong.Location = new System.Drawing.Point(165, 562);
            this.nudSoLuong.Size = new System.Drawing.Size(95, 28);
            this.nudSoLuong.Minimum = 1;
            this.nudSoLuong.Maximum = 999;
            this.nudSoLuong.Value = 1;
            this.Controls.Add(this.nudSoLuong);
            this.btnThem = new System.Windows.Forms.Button();
            this.btnThem.Name = "btnThem";
            this.btnThem.Location = new System.Drawing.Point(610, 558);
            this.btnThem.Size = new System.Drawing.Size(170, 36);
            this.btnThem.Text = "Thêm vào giỏ";
            this.btnThem.UseVisualStyleBackColor = true;
            this.btnThem.Click += this.btnThem_Click;
            this.Controls.Add(this.btnThem);
            this.btnDong = new System.Windows.Forms.Button();
            this.btnDong.Name = "btnDong";
            this.btnDong.Location = new System.Drawing.Point(795, 558);
            this.btnDong.Size = new System.Drawing.Size(100, 36);
            this.btnDong.Text = "Đóng";
            this.btnDong.UseVisualStyleBackColor = true;
            this.btnDong.Click += this.btnDong_Click;
            this.Controls.Add(this.btnDong);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(920, 635);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Name = "FrmChiTietSanPham";
            this.Text = "Chi tiết sản phẩm";
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        private System.Windows.Forms.Label lblMaSP;
        private System.Windows.Forms.TextBox txtMaSP;
        private System.Windows.Forms.Label lblTenSP;
        private System.Windows.Forms.TextBox txtTenSP;
        private System.Windows.Forms.Label lblNhom;
        private System.Windows.Forms.TextBox txtNhom;
        private System.Windows.Forms.Label lblNSX;
        private System.Windows.Forms.TextBox txtNSX;
        private System.Windows.Forms.Label lblGia;
        private System.Windows.Forms.TextBox txtGia;
        private System.Windows.Forms.Label lblTinhTrang;
        private System.Windows.Forms.TextBox txtTinhTrang;
        private System.Windows.Forms.Label lblMoTa;
        private System.Windows.Forms.TextBox txtMoTa;
        private System.Windows.Forms.Label lblThongSo;
        private System.Windows.Forms.TextBox txtThongSo;
        private System.Windows.Forms.PictureBox picSanPham;
        private System.Windows.Forms.ComboBox cboHinhAnh;
        private System.Windows.Forms.Label lblSL;
        private System.Windows.Forms.NumericUpDown nudSoLuong;
        private System.Windows.Forms.Button btnThem;
        private System.Windows.Forms.Button btnDong;
    }
}
