namespace QuanLyCuaHangOnline
{
    partial class FrmTaiKhoan
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.lblLogin = new System.Windows.Forms.Label();
            this.lblLogin.Name = "lblLogin";
            this.lblLogin.Location = new System.Drawing.Point(25, 25);
            this.lblLogin.Size = new System.Drawing.Size(300, 26);
            this.lblLogin.Text = "Đăng nhập";
            this.Controls.Add(this.lblLogin);
            this.lblUser = new System.Windows.Forms.Label();
            this.lblUser.Name = "lblUser";
            this.lblUser.Location = new System.Drawing.Point(25, 92);
            this.lblUser.Size = new System.Drawing.Size(135, 26);
            this.lblUser.Text = "Tên đăng nhập";
            this.Controls.Add(this.lblUser);
            this.txtUser = new System.Windows.Forms.TextBox();
            this.txtUser.Name = "txtUser";
            this.txtUser.Location = new System.Drawing.Point(170, 87);
            this.txtUser.Size = new System.Drawing.Size(190, 27);
            this.Controls.Add(this.txtUser);
            this.lblPass = new System.Windows.Forms.Label();
            this.lblPass.Name = "lblPass";
            this.lblPass.Location = new System.Drawing.Point(25, 145);
            this.lblPass.Size = new System.Drawing.Size(135, 26);
            this.lblPass.Text = "Mật khẩu";
            this.Controls.Add(this.lblPass);
            this.txtPass = new System.Windows.Forms.TextBox();
            this.txtPass.Name = "txtPass";
            this.txtPass.Location = new System.Drawing.Point(170, 140);
            this.txtPass.Size = new System.Drawing.Size(190, 27);
            this.txtPass.UseSystemPasswordChar = true;
            this.Controls.Add(this.txtPass);
            this.btnDangNhap = new System.Windows.Forms.Button();
            this.btnDangNhap.Name = "btnDangNhap";
            this.btnDangNhap.Location = new System.Drawing.Point(170, 200);
            this.btnDangNhap.Size = new System.Drawing.Size(190, 36);
            this.btnDangNhap.Text = "Đăng nhập";
            this.btnDangNhap.UseVisualStyleBackColor = true;
            this.btnDangNhap.Click += this.btnDangNhap_Click;
            this.Controls.Add(this.btnDangNhap);
            this.lblRegister = new System.Windows.Forms.Label();
            this.lblRegister.Name = "lblRegister";
            this.lblRegister.Location = new System.Drawing.Point(410, 25);
            this.lblRegister.Size = new System.Drawing.Size(500, 26);
            this.lblRegister.Text = "Đăng ký tài khoản mới";
            this.Controls.Add(this.lblRegister);
            this.lblHoTen = new System.Windows.Forms.Label();
            this.lblHoTen.Name = "lblHoTen";
            this.lblHoTen.Location = new System.Drawing.Point(410, 91);
            this.lblHoTen.Size = new System.Drawing.Size(165, 26);
            this.lblHoTen.Text = "Họ tên";
            this.Controls.Add(this.lblHoTen);
            this.txtHoTen = new System.Windows.Forms.TextBox();
            this.txtHoTen.Name = "txtHoTen";
            this.txtHoTen.Location = new System.Drawing.Point(580, 86);
            this.txtHoTen.Size = new System.Drawing.Size(335, 27);
            this.Controls.Add(this.txtHoTen);
            this.lblNgaySinh = new System.Windows.Forms.Label();
            this.lblNgaySinh.Name = "lblNgaySinh";
            this.lblNgaySinh.Location = new System.Drawing.Point(410, 143);
            this.lblNgaySinh.Size = new System.Drawing.Size(165, 26);
            this.lblNgaySinh.Text = "Ngày sinh";
            this.Controls.Add(this.lblNgaySinh);
            this.dtpNgaySinh = new System.Windows.Forms.DateTimePicker();
            this.dtpNgaySinh.Name = "dtpNgaySinh";
            this.dtpNgaySinh.Location = new System.Drawing.Point(580, 138);
            this.dtpNgaySinh.Size = new System.Drawing.Size(335, 28);
            this.dtpNgaySinh.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.dtpNgaySinh.CustomFormat = "dd/MM/yyyy";
            this.dtpNgaySinh.Value = new System.DateTime(2005, 1, 1);
            this.Controls.Add(this.dtpNgaySinh);
            this.lblGiayTo = new System.Windows.Forms.Label();
            this.lblGiayTo.Name = "lblGiayTo";
            this.lblGiayTo.Location = new System.Drawing.Point(410, 195);
            this.lblGiayTo.Size = new System.Drawing.Size(165, 26);
            this.lblGiayTo.Text = "CMND / Passport";
            this.Controls.Add(this.lblGiayTo);
            this.txtGiayTo = new System.Windows.Forms.TextBox();
            this.txtGiayTo.Name = "txtGiayTo";
            this.txtGiayTo.Location = new System.Drawing.Point(580, 190);
            this.txtGiayTo.Size = new System.Drawing.Size(335, 27);
            this.Controls.Add(this.txtGiayTo);
            this.lblDiaChi = new System.Windows.Forms.Label();
            this.lblDiaChi.Name = "lblDiaChi";
            this.lblDiaChi.Location = new System.Drawing.Point(410, 247);
            this.lblDiaChi.Size = new System.Drawing.Size(165, 26);
            this.lblDiaChi.Text = "Địa chỉ";
            this.Controls.Add(this.lblDiaChi);
            this.txtDiaChi = new System.Windows.Forms.TextBox();
            this.txtDiaChi.Name = "txtDiaChi";
            this.txtDiaChi.Location = new System.Drawing.Point(580, 242);
            this.txtDiaChi.Size = new System.Drawing.Size(335, 27);
            this.Controls.Add(this.txtDiaChi);
            this.lblDienThoai = new System.Windows.Forms.Label();
            this.lblDienThoai.Name = "lblDienThoai";
            this.lblDienThoai.Location = new System.Drawing.Point(410, 299);
            this.lblDienThoai.Size = new System.Drawing.Size(165, 26);
            this.lblDienThoai.Text = "Điện thoại";
            this.Controls.Add(this.lblDienThoai);
            this.txtDienThoai = new System.Windows.Forms.TextBox();
            this.txtDienThoai.Name = "txtDienThoai";
            this.txtDienThoai.Location = new System.Drawing.Point(580, 294);
            this.txtDienThoai.Size = new System.Drawing.Size(335, 27);
            this.Controls.Add(this.txtDienThoai);
            this.lblUsername = new System.Windows.Forms.Label();
            this.lblUsername.Name = "lblUsername";
            this.lblUsername.Location = new System.Drawing.Point(410, 351);
            this.lblUsername.Size = new System.Drawing.Size(165, 26);
            this.lblUsername.Text = "Tên đăng nhập";
            this.Controls.Add(this.lblUsername);
            this.txtUsername = new System.Windows.Forms.TextBox();
            this.txtUsername.Name = "txtUsername";
            this.txtUsername.Location = new System.Drawing.Point(580, 346);
            this.txtUsername.Size = new System.Drawing.Size(335, 27);
            this.Controls.Add(this.txtUsername);
            this.lblPassword = new System.Windows.Forms.Label();
            this.lblPassword.Name = "lblPassword";
            this.lblPassword.Location = new System.Drawing.Point(410, 403);
            this.lblPassword.Size = new System.Drawing.Size(165, 26);
            this.lblPassword.Text = "Mật khẩu";
            this.Controls.Add(this.lblPassword);
            this.txtPassword = new System.Windows.Forms.TextBox();
            this.txtPassword.Name = "txtPassword";
            this.txtPassword.Location = new System.Drawing.Point(580, 398);
            this.txtPassword.Size = new System.Drawing.Size(335, 27);
            this.txtPassword.UseSystemPasswordChar = true;
            this.Controls.Add(this.txtPassword);
            this.lblEmail = new System.Windows.Forms.Label();
            this.lblEmail.Name = "lblEmail";
            this.lblEmail.Location = new System.Drawing.Point(410, 455);
            this.lblEmail.Size = new System.Drawing.Size(165, 26);
            this.lblEmail.Text = "Email";
            this.Controls.Add(this.lblEmail);
            this.txtEmail = new System.Windows.Forms.TextBox();
            this.txtEmail.Name = "txtEmail";
            this.txtEmail.Location = new System.Drawing.Point(580, 450);
            this.txtEmail.Size = new System.Drawing.Size(335, 27);
            this.Controls.Add(this.txtEmail);
            this.btnDangKy = new System.Windows.Forms.Button();
            this.btnDangKy.Name = "btnDangKy";
            this.btnDangKy.Location = new System.Drawing.Point(715, 525);
            this.btnDangKy.Size = new System.Drawing.Size(200, 36);
            this.btnDangKy.Text = "Đăng ký";
            this.btnDangKy.UseVisualStyleBackColor = true;
            this.btnDangKy.Click += this.btnDangKy_Click;
            this.Controls.Add(this.btnDangKy);
            this.lblOptional = new System.Windows.Forms.Label();
            this.lblOptional.Name = "lblOptional";
            this.lblOptional.Location = new System.Drawing.Point(25, 305);
            this.lblOptional.Size = new System.Drawing.Size(320, 26);
            this.lblOptional.Text = "Email không bắt buộc.";
            this.Controls.Add(this.lblOptional);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(940, 600);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Name = "FrmTaiKhoan";
            this.Text = "Tài khoản - Đăng nhập / Đăng ký";
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        private System.Windows.Forms.Label lblLogin;
        private System.Windows.Forms.Label lblUser;
        private System.Windows.Forms.TextBox txtUser;
        private System.Windows.Forms.Label lblPass;
        private System.Windows.Forms.TextBox txtPass;
        private System.Windows.Forms.Button btnDangNhap;
        private System.Windows.Forms.Label lblRegister;
        private System.Windows.Forms.Label lblHoTen;
        private System.Windows.Forms.TextBox txtHoTen;
        private System.Windows.Forms.Label lblNgaySinh;
        private System.Windows.Forms.DateTimePicker dtpNgaySinh;
        private System.Windows.Forms.Label lblGiayTo;
        private System.Windows.Forms.TextBox txtGiayTo;
        private System.Windows.Forms.Label lblDiaChi;
        private System.Windows.Forms.TextBox txtDiaChi;
        private System.Windows.Forms.Label lblDienThoai;
        private System.Windows.Forms.TextBox txtDienThoai;
        private System.Windows.Forms.Label lblUsername;
        private System.Windows.Forms.TextBox txtUsername;
        private System.Windows.Forms.Label lblPassword;
        private System.Windows.Forms.TextBox txtPassword;
        private System.Windows.Forms.Label lblEmail;
        private System.Windows.Forms.TextBox txtEmail;
        private System.Windows.Forms.Button btnDangKy;
        private System.Windows.Forms.Label lblOptional;
    }
}
