using System;
using System.Windows.Forms;

namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmChuyenLe
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing) { if (disposing && components != null) components.Dispose(); base.Dispose(disposing); }
        private Label label1;
        private TextBox txtMa;
        private Label label2;
        private ComboBox cboTour;
        private Label label3;
        private DateTimePicker dtDi;
        private Label label4;
        private Label lblNgayVe;
        private Label label6;
        private TextBox txtDon;
        private Button btnThem;
        private Button btnDongDK;
        private DataGridView dgv;
        private Button btnDong;
        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F,96F);
            this.AutoScaleMode = AutoScaleMode.Dpi;
            this.ClientSize = new System.Drawing.Size(1340,528);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Text = "Lịch chuyến khách lẻ";
            this.Name = "FrmChuyenLe";
            this.StartPosition = FormStartPosition.CenterParent;
            this.BackColor = System.Drawing.SystemColors.Control;
            this.MinimumSize = new System.Drawing.Size(1356,567);
            this.label1 = new Label();
            this.label1.Name = "label1";
            this.label1.SetBounds(32,18,117,24);
            this.label1.Text = "Mã chuyến:";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.label1);
            this.txtMa = new TextBox();
            this.txtMa.Name = "txtMa";
            this.txtMa.SetBounds(149,18,190,24);
            this.txtMa.MaxLength = 1000;
            this.Controls.Add(this.txtMa);
            this.label2 = new Label();
            this.label2.Name = "label2";
            this.label2.SetBounds(376,18,59,24);
            this.label2.Text = "Tour:";
            this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.label2);
            this.cboTour = new ComboBox();
            this.cboTour.Name = "cboTour";
            this.cboTour.SetBounds(434,18,439,24);
            this.cboTour.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboTour.DropDownWidth = 600;
            this.Controls.Add(this.cboTour);
            this.cboTour.SelectedIndexChanged += TinhNgayVe;
            this.label3 = new Label();
            this.label3.Name = "label3";
            this.label3.SetBounds(32,53,117,24);
            this.label3.Text = "Ngày đi:";
            this.label3.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.label3);
            this.dtDi = new DateTimePicker();
            this.dtDi.Name = "dtDi";
            this.dtDi.SetBounds(149,53,190,24);
            this.dtDi.Format = DateTimePickerFormat.Custom;
            this.dtDi.CustomFormat = "dd/MM/yyyy";
            this.Controls.Add(this.dtDi);
            this.dtDi.ValueChanged += TinhNgayVe;
            this.label4 = new Label();
            this.label4.Name = "label4";
            this.label4.SetBounds(376,53,102,24);
            this.label4.Text = "Ngày về:";
            this.label4.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.label4);
            this.lblNgayVe = new Label();
            this.lblNgayVe.Name = "lblNgayVe";
            this.lblNgayVe.SetBounds(478,53,219,24);
            this.lblNgayVe.Text = "-";
            this.lblNgayVe.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblNgayVe.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.Controls.Add(this.lblNgayVe);
            this.label6 = new Label();
            this.label6.Name = "label6";
            this.label6.SetBounds(32,88,139,24);
            this.label6.Text = "Địa điểm đón:";
            this.label6.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.label6);
            this.txtDon = new TextBox();
            this.txtDon.Name = "txtDon";
            this.txtDon.SetBounds(178,88,731,24);
            this.txtDon.MaxLength = 1000;
            this.Controls.Add(this.txtDon);
            this.btnThem = new Button();
            this.btnThem.Name = "btnThem";
            this.btnThem.SetBounds(961,85,161,32);
            this.btnThem.Text = "Tạo chuyến";
            this.btnThem.UseVisualStyleBackColor = false;
            this.btnThem.FlatStyle = FlatStyle.Flat;
            this.btnThem.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnThem.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.Controls.Add(this.btnThem);
            this.btnThem.Click += btnThem_Click;
            this.btnDongDK = new Button();
            this.btnDongDK.Name = "btnDongDK";
            this.btnDongDK.SetBounds(1137,85,168,32);
            this.btnDongDK.Text = "Đóng đăng ký";
            this.btnDongDK.UseVisualStyleBackColor = false;
            this.btnDongDK.FlatStyle = FlatStyle.Flat;
            this.btnDongDK.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnDongDK.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.Controls.Add(this.btnDongDK);
            this.btnDongDK.Click += btnDongDK_Click;
            this.dgv = new DataGridView();
            this.dgv.Name = "dgv";
            this.dgv.SetBounds(32,128,1273,345);
            this.dgv.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            this.dgv.BackgroundColor = System.Drawing.Color.White;
            this.dgv.GridColor = System.Drawing.Color.FromArgb(220,220,220);
            this.dgv.BorderStyle = BorderStyle.FixedSingle;
            this.dgv.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
            this.dgv.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgv.MultiSelect = false;
            this.dgv.ReadOnly = true;
            this.dgv.AllowUserToAddRows = false;
            this.dgv.AllowUserToDeleteRows = false;
            this.dgv.RowHeadersWidth = 30;
            this.dgv.RowTemplate.Height = 25;
            this.dgv.ColumnHeadersHeight = 25;
            this.dgv.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.dgv.EnableHeadersVisualStyles = false;
            this.dgv.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.SystemColors.Control;
            this.dgv.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(205,232,255);
            this.dgv.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgv.DefaultCellStyle.NullValue = "";
            this.dgv.DefaultCellStyle.Format = "";
            this.Controls.Add(this.dgv);
            this.dgv.DataBindingComplete += FormHelper.DinhDangBang;
            this.dgv.SizeChanged += FormHelper.KichThuocBangThayDoi;
            this.dgv.CellValueChanged += FormHelper.DuLieuOThayDoi;
            this.btnDong = new Button();
            this.btnDong.Name = "btnDong";
            this.btnDong.SetBounds(1164,485,146,30);
            this.btnDong.Text = "Đóng";
            this.btnDong.UseVisualStyleBackColor = false;
            this.btnDong.FlatStyle = FlatStyle.Flat;
            this.btnDong.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnDong.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.Controls.Add(this.btnDong);
            this.btnDong.Click += btnDong_Click;
            this.btnDong.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            this.Load += FrmChuyenLe_Load;
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
