using System;
using System.Windows.Forms;

namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmDanhMuc
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing) { if (disposing && components != null) components.Dispose(); base.Dispose(disposing); }
        private TabControl tabDanhMuc;
        private TabPage tabDanhMucPage0;
        private TabPage tabDanhMucPage1;
        private TabPage tabDanhMucPage2;
        private TabPage tabDanhMucPage3;
        private DataGridView dgvPT;
        private DataGridView dgvDB;
        private DataGridView dgvHDV;
        private DataGridView dgvDTQ;
        private Label label1;
        private TextBox txtPTMa;
        private Label label2;
        private TextBox txtPTTen;
        private Label label3;
        private TextBox txtPTGhiChu;
        private Button btnThemPT;
        private Label label4;
        private TextBox txtDBMa;
        private Label label5;
        private TextBox txtDBTen;
        private Label label6;
        private TextBox txtDBDiaChi;
        private Label label7;
        private TextBox txtDBDT;
        private Button btnThemDB;
        private Label label8;
        private TextBox txtHDVMa;
        private Label label9;
        private TextBox txtHDVTen;
        private Label label10;
        private TextBox txtHDVDT;
        private Label label11;
        private NumericUpDown numLuong;
        private Button btnThemHDV;
        private Label label12;
        private TextBox txtDTQMa;
        private Label label13;
        private TextBox txtDTQTen;
        private Label label14;
        private TextBox txtDTQDiaDiem;
        private Label label15;
        private TextBox txtDTQNoiDung;
        private Label label16;
        private TextBox txtDTQYNghia;
        private Button btnThemDTQ;
        private Button btnDong;
        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F,96F);
            this.AutoScaleMode = AutoScaleMode.Dpi;
            this.ClientSize = new System.Drawing.Size(1340,568);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Text = "Danh mục";
            this.Name = "FrmDanhMuc";
            this.StartPosition = FormStartPosition.CenterParent;
            this.BackColor = System.Drawing.SystemColors.Control;
            this.MinimumSize = new System.Drawing.Size(1356,607);
            this.tabDanhMuc = new TabControl();
            this.tabDanhMuc.Name = "tabDanhMuc";
            this.tabDanhMuc.SetBounds(29,16,1281,497);
            this.tabDanhMuc.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            this.Controls.Add(this.tabDanhMuc);
            this.tabDanhMucPage0 = new TabPage();
            this.tabDanhMucPage0.Name = "tabDanhMucPage0";
            this.tabDanhMucPage0.SetBounds(0,0,1270,472);
            this.tabDanhMucPage0.Text = "Phương tiện";
            this.tabDanhMucPage0.BackColor = System.Drawing.Color.White;
            this.tabDanhMuc.Controls.Add(this.tabDanhMucPage0);
            this.tabDanhMucPage1 = new TabPage();
            this.tabDanhMucPage1.Name = "tabDanhMucPage1";
            this.tabDanhMucPage1.SetBounds(0,0,1270,472);
            this.tabDanhMucPage1.Text = "Điểm bán vé";
            this.tabDanhMucPage1.BackColor = System.Drawing.Color.White;
            this.tabDanhMuc.Controls.Add(this.tabDanhMucPage1);
            this.tabDanhMucPage2 = new TabPage();
            this.tabDanhMucPage2.Name = "tabDanhMucPage2";
            this.tabDanhMucPage2.SetBounds(0,0,1270,472);
            this.tabDanhMucPage2.Text = "Hướng dẫn viên";
            this.tabDanhMucPage2.BackColor = System.Drawing.Color.White;
            this.tabDanhMuc.Controls.Add(this.tabDanhMucPage2);
            this.tabDanhMucPage3 = new TabPage();
            this.tabDanhMucPage3.Name = "tabDanhMucPage3";
            this.tabDanhMucPage3.SetBounds(0,0,1270,472);
            this.tabDanhMucPage3.Text = "Điểm tham quan";
            this.tabDanhMucPage3.BackColor = System.Drawing.Color.White;
            this.tabDanhMuc.Controls.Add(this.tabDanhMucPage3);
            this.dgvPT = new DataGridView();
            this.dgvPT.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            this.dgvPT.Name = "dgvPT";
            this.dgvPT.SetBounds(15,10,1243,300);
            this.dgvPT.BackgroundColor = System.Drawing.Color.White;
            this.dgvPT.GridColor = System.Drawing.Color.FromArgb(220,220,220);
            this.dgvPT.BorderStyle = BorderStyle.FixedSingle;
            this.dgvPT.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
            this.dgvPT.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvPT.MultiSelect = false;
            this.dgvPT.ReadOnly = true;
            this.dgvPT.AllowUserToAddRows = false;
            this.dgvPT.AllowUserToDeleteRows = false;
            this.dgvPT.RowHeadersWidth = 30;
            this.dgvPT.RowTemplate.Height = 25;
            this.dgvPT.ColumnHeadersHeight = 25;
            this.dgvPT.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.dgvPT.EnableHeadersVisualStyles = false;
            this.dgvPT.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.SystemColors.Control;
            this.dgvPT.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(205,232,255);
            this.dgvPT.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgvPT.DefaultCellStyle.NullValue = "";
            this.dgvPT.DefaultCellStyle.Format = "";
            this.tabDanhMucPage0.Controls.Add(this.dgvPT);
            this.dgvPT.DataBindingComplete += FormHelper.DinhDangBang;
            this.dgvPT.SizeChanged += FormHelper.KichThuocBangThayDoi;
            this.dgvPT.CellValueChanged += FormHelper.DuLieuOThayDoi;
            this.dgvDB = new DataGridView();
            this.dgvDB.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            this.dgvDB.Name = "dgvDB";
            this.dgvDB.SetBounds(15,10,1243,300);
            this.dgvDB.BackgroundColor = System.Drawing.Color.White;
            this.dgvDB.GridColor = System.Drawing.Color.FromArgb(220,220,220);
            this.dgvDB.BorderStyle = BorderStyle.FixedSingle;
            this.dgvDB.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
            this.dgvDB.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvDB.MultiSelect = false;
            this.dgvDB.ReadOnly = true;
            this.dgvDB.AllowUserToAddRows = false;
            this.dgvDB.AllowUserToDeleteRows = false;
            this.dgvDB.RowHeadersWidth = 30;
            this.dgvDB.RowTemplate.Height = 25;
            this.dgvDB.ColumnHeadersHeight = 25;
            this.dgvDB.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.dgvDB.EnableHeadersVisualStyles = false;
            this.dgvDB.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.SystemColors.Control;
            this.dgvDB.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(205,232,255);
            this.dgvDB.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgvDB.DefaultCellStyle.NullValue = "";
            this.dgvDB.DefaultCellStyle.Format = "";
            this.tabDanhMucPage1.Controls.Add(this.dgvDB);
            this.dgvDB.DataBindingComplete += FormHelper.DinhDangBang;
            this.dgvDB.SizeChanged += FormHelper.KichThuocBangThayDoi;
            this.dgvDB.CellValueChanged += FormHelper.DuLieuOThayDoi;
            this.dgvHDV = new DataGridView();
            this.dgvHDV.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            this.dgvHDV.Name = "dgvHDV";
            this.dgvHDV.SetBounds(15,10,1243,300);
            this.dgvHDV.BackgroundColor = System.Drawing.Color.White;
            this.dgvHDV.GridColor = System.Drawing.Color.FromArgb(220,220,220);
            this.dgvHDV.BorderStyle = BorderStyle.FixedSingle;
            this.dgvHDV.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
            this.dgvHDV.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvHDV.MultiSelect = false;
            this.dgvHDV.ReadOnly = true;
            this.dgvHDV.AllowUserToAddRows = false;
            this.dgvHDV.AllowUserToDeleteRows = false;
            this.dgvHDV.RowHeadersWidth = 30;
            this.dgvHDV.RowTemplate.Height = 25;
            this.dgvHDV.ColumnHeadersHeight = 25;
            this.dgvHDV.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.dgvHDV.EnableHeadersVisualStyles = false;
            this.dgvHDV.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.SystemColors.Control;
            this.dgvHDV.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(205,232,255);
            this.dgvHDV.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgvHDV.DefaultCellStyle.NullValue = "";
            this.dgvHDV.DefaultCellStyle.Format = "";
            this.tabDanhMucPage2.Controls.Add(this.dgvHDV);
            this.dgvHDV.DataBindingComplete += FormHelper.DinhDangBang;
            this.dgvHDV.SizeChanged += FormHelper.KichThuocBangThayDoi;
            this.dgvHDV.CellValueChanged += FormHelper.DuLieuOThayDoi;
            this.dgvDTQ = new DataGridView();
            this.dgvDTQ.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            this.dgvDTQ.Name = "dgvDTQ";
            this.dgvDTQ.SetBounds(15,10,1243,300);
            this.dgvDTQ.BackgroundColor = System.Drawing.Color.White;
            this.dgvDTQ.GridColor = System.Drawing.Color.FromArgb(220,220,220);
            this.dgvDTQ.BorderStyle = BorderStyle.FixedSingle;
            this.dgvDTQ.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
            this.dgvDTQ.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvDTQ.MultiSelect = false;
            this.dgvDTQ.ReadOnly = true;
            this.dgvDTQ.AllowUserToAddRows = false;
            this.dgvDTQ.AllowUserToDeleteRows = false;
            this.dgvDTQ.RowHeadersWidth = 30;
            this.dgvDTQ.RowTemplate.Height = 25;
            this.dgvDTQ.ColumnHeadersHeight = 25;
            this.dgvDTQ.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.dgvDTQ.EnableHeadersVisualStyles = false;
            this.dgvDTQ.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.SystemColors.Control;
            this.dgvDTQ.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(205,232,255);
            this.dgvDTQ.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgvDTQ.DefaultCellStyle.NullValue = "";
            this.dgvDTQ.DefaultCellStyle.Format = "";
            this.tabDanhMucPage3.Controls.Add(this.dgvDTQ);
            this.dgvDTQ.DataBindingComplete += FormHelper.DinhDangBang;
            this.dgvDTQ.SizeChanged += FormHelper.KichThuocBangThayDoi;
            this.dgvDTQ.CellValueChanged += FormHelper.DuLieuOThayDoi;
            this.label1 = new Label();
            this.label1.Name = "label1";
            this.label1.SetBounds(18,324,111,24);
            this.label1.Text = "Mã PT:";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabDanhMucPage0.Controls.Add(this.label1);
            this.txtPTMa = new TextBox();
            this.txtPTMa.Name = "txtPTMa";
            this.txtPTMa.SetBounds(149,324,219,24);
            this.txtPTMa.MaxLength = 1000;
            this.tabDanhMucPage0.Controls.Add(this.txtPTMa);
            this.label2 = new Label();
            this.label2.Name = "label2";
            this.label2.SetBounds(427,324,111,24);
            this.label2.Text = "Tên PT:";
            this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabDanhMucPage0.Controls.Add(this.label2);
            this.txtPTTen = new TextBox();
            this.txtPTTen.Name = "txtPTTen";
            this.txtPTTen.SetBounds(559,324,366,24);
            this.txtPTTen.MaxLength = 1000;
            this.tabDanhMucPage0.Controls.Add(this.txtPTTen);
            this.label3 = new Label();
            this.label3.Name = "label3";
            this.label3.SetBounds(18,359,111,24);
            this.label3.Text = "Ghi chú:";
            this.label3.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabDanhMucPage0.Controls.Add(this.label3);
            this.txtPTGhiChu = new TextBox();
            this.txtPTGhiChu.Name = "txtPTGhiChu";
            this.txtPTGhiChu.SetBounds(149,359,658,24);
            this.txtPTGhiChu.MaxLength = 1000;
            this.tabDanhMucPage0.Controls.Add(this.txtPTGhiChu);
            this.btnThemPT = new Button();
            this.btnThemPT.Name = "btnThemPT";
            this.btnThemPT.SetBounds(954,356,146,32);
            this.btnThemPT.Text = "Thêm";
            this.btnThemPT.UseVisualStyleBackColor = false;
            this.btnThemPT.FlatStyle = FlatStyle.Flat;
            this.btnThemPT.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnThemPT.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.tabDanhMucPage0.Controls.Add(this.btnThemPT);
            this.btnThemPT.Click += btnThemPT_Click;
            this.label4 = new Label();
            this.label4.Name = "label4";
            this.label4.SetBounds(18,324,123,24);
            this.label4.Text = "Mã điểm bán:";
            this.label4.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabDanhMucPage1.Controls.Add(this.label4);
            this.txtDBMa = new TextBox();
            this.txtDBMa.Name = "txtDBMa";
            this.txtDBMa.SetBounds(149,324,219,24);
            this.txtDBMa.MaxLength = 1000;
            this.tabDanhMucPage1.Controls.Add(this.txtDBMa);
            this.label5 = new Label();
            this.label5.Name = "label5";
            this.label5.SetBounds(427,324,123,24);
            this.label5.Text = "Tên điểm bán:";
            this.label5.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabDanhMucPage1.Controls.Add(this.label5);
            this.txtDBTen = new TextBox();
            this.txtDBTen.Name = "txtDBTen";
            this.txtDBTen.SetBounds(559,324,410,24);
            this.txtDBTen.MaxLength = 1000;
            this.tabDanhMucPage1.Controls.Add(this.txtDBTen);
            this.label6 = new Label();
            this.label6.Name = "label6";
            this.label6.SetBounds(18,359,123,24);
            this.label6.Text = "Địa chỉ:";
            this.label6.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabDanhMucPage1.Controls.Add(this.label6);
            this.txtDBDiaChi = new TextBox();
            this.txtDBDiaChi.Name = "txtDBDiaChi";
            this.txtDBDiaChi.SetBounds(149,359,658,24);
            this.txtDBDiaChi.MaxLength = 1000;
            this.tabDanhMucPage1.Controls.Add(this.txtDBDiaChi);
            this.label7 = new Label();
            this.label7.Name = "label7";
            this.label7.SetBounds(18,394,123,24);
            this.label7.Text = "Điện thoại:";
            this.label7.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabDanhMucPage1.Controls.Add(this.label7);
            this.txtDBDT = new TextBox();
            this.txtDBDT.Name = "txtDBDT";
            this.txtDBDT.SetBounds(149,394,263,24);
            this.txtDBDT.MaxLength = 1000;
            this.tabDanhMucPage1.Controls.Add(this.txtDBDT);
            this.btnThemDB = new Button();
            this.btnThemDB.Name = "btnThemDB";
            this.btnThemDB.SetBounds(954,392,146,32);
            this.btnThemDB.Text = "Thêm";
            this.btnThemDB.UseVisualStyleBackColor = false;
            this.btnThemDB.FlatStyle = FlatStyle.Flat;
            this.btnThemDB.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnThemDB.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.tabDanhMucPage1.Controls.Add(this.btnThemDB);
            this.btnThemDB.Click += btnThemDB_Click;
            this.label8 = new Label();
            this.label8.Name = "label8";
            this.label8.SetBounds(18,324,123,24);
            this.label8.Text = "Mã HDV:";
            this.label8.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabDanhMucPage2.Controls.Add(this.label8);
            this.txtHDVMa = new TextBox();
            this.txtHDVMa.Name = "txtHDVMa";
            this.txtHDVMa.SetBounds(149,324,219,24);
            this.txtHDVMa.MaxLength = 1000;
            this.tabDanhMucPage2.Controls.Add(this.txtHDVMa);
            this.label9 = new Label();
            this.label9.Name = "label9";
            this.label9.SetBounds(427,324,123,24);
            this.label9.Text = "Họ tên:";
            this.label9.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabDanhMucPage2.Controls.Add(this.label9);
            this.txtHDVTen = new TextBox();
            this.txtHDVTen.Name = "txtHDVTen";
            this.txtHDVTen.SetBounds(559,324,410,24);
            this.txtHDVTen.MaxLength = 1000;
            this.tabDanhMucPage2.Controls.Add(this.txtHDVTen);
            this.label10 = new Label();
            this.label10.Name = "label10";
            this.label10.SetBounds(18,359,123,24);
            this.label10.Text = "Điện thoại:";
            this.label10.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabDanhMucPage2.Controls.Add(this.label10);
            this.txtHDVDT = new TextBox();
            this.txtHDVDT.Name = "txtHDVDT";
            this.txtHDVDT.SetBounds(149,359,219,24);
            this.txtHDVDT.MaxLength = 1000;
            this.tabDanhMucPage2.Controls.Add(this.txtHDVDT);
            this.label11 = new Label();
            this.label11.Name = "label11";
            this.label11.SetBounds(427,359,155,24);
            this.label11.Text = "Lương cơ bản:";
            this.label11.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabDanhMucPage2.Controls.Add(this.label11);
            this.numLuong = new NumericUpDown();
            this.numLuong.Name = "numLuong";
            this.numLuong.SetBounds(603,359,249,24);
            this.numLuong.Minimum = 0M;
            this.numLuong.Maximum = 1000000000M;
            this.numLuong.Value = 9000000M;
            this.numLuong.TextAlign = HorizontalAlignment.Right;
            this.numLuong.ThousandsSeparator = true;
            this.numLuong.Increment = 100000M;
            this.tabDanhMucPage2.Controls.Add(this.numLuong);
            this.btnThemHDV = new Button();
            this.btnThemHDV.Name = "btnThemHDV";
            this.btnThemHDV.SetBounds(954,356,146,32);
            this.btnThemHDV.Text = "Thêm";
            this.btnThemHDV.UseVisualStyleBackColor = false;
            this.btnThemHDV.FlatStyle = FlatStyle.Flat;
            this.btnThemHDV.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnThemHDV.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.tabDanhMucPage2.Controls.Add(this.btnThemHDV);
            this.btnThemHDV.Click += btnThemHDV_Click;
            this.label12 = new Label();
            this.label12.Name = "label12";
            this.label12.SetBounds(18,324,123,24);
            this.label12.Text = "Mã điểm TQ:";
            this.label12.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabDanhMucPage3.Controls.Add(this.label12);
            this.txtDTQMa = new TextBox();
            this.txtDTQMa.Name = "txtDTQMa";
            this.txtDTQMa.SetBounds(149,324,219,24);
            this.txtDTQMa.MaxLength = 1000;
            this.tabDanhMucPage3.Controls.Add(this.txtDTQMa);
            this.label13 = new Label();
            this.label13.Name = "label13";
            this.label13.SetBounds(427,324,123,24);
            this.label13.Text = "Tên điểm TQ:";
            this.label13.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabDanhMucPage3.Controls.Add(this.label13);
            this.txtDTQTen = new TextBox();
            this.txtDTQTen.Name = "txtDTQTen";
            this.txtDTQTen.SetBounds(559,324,439,24);
            this.txtDTQTen.MaxLength = 1000;
            this.tabDanhMucPage3.Controls.Add(this.txtDTQTen);
            this.label14 = new Label();
            this.label14.Name = "label14";
            this.label14.SetBounds(18,359,123,24);
            this.label14.Text = "Địa điểm:";
            this.label14.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabDanhMucPage3.Controls.Add(this.label14);
            this.txtDTQDiaDiem = new TextBox();
            this.txtDTQDiaDiem.Name = "txtDTQDiaDiem";
            this.txtDTQDiaDiem.SetBounds(149,359,848,24);
            this.txtDTQDiaDiem.MaxLength = 1000;
            this.tabDanhMucPage3.Controls.Add(this.txtDTQDiaDiem);
            this.label15 = new Label();
            this.label15.Name = "label15";
            this.label15.SetBounds(18,394,123,24);
            this.label15.Text = "Nội dung:";
            this.label15.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabDanhMucPage3.Controls.Add(this.label15);
            this.txtDTQNoiDung = new TextBox();
            this.txtDTQNoiDung.Name = "txtDTQNoiDung";
            this.txtDTQNoiDung.SetBounds(149,394,848,24);
            this.txtDTQNoiDung.MaxLength = 1000;
            this.tabDanhMucPage3.Controls.Add(this.txtDTQNoiDung);
            this.label16 = new Label();
            this.label16.Name = "label16";
            this.label16.SetBounds(18,429,123,24);
            this.label16.Text = "Ý nghĩa:";
            this.label16.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabDanhMucPage3.Controls.Add(this.label16);
            this.txtDTQYNghia = new TextBox();
            this.txtDTQYNghia.Name = "txtDTQYNghia";
            this.txtDTQYNghia.SetBounds(149,429,848,24);
            this.txtDTQYNghia.MaxLength = 1000;
            this.tabDanhMucPage3.Controls.Add(this.txtDTQYNghia);
            this.btnThemDTQ = new Button();
            this.btnThemDTQ.Name = "btnThemDTQ";
            this.btnThemDTQ.SetBounds(1042,426,146,32);
            this.btnThemDTQ.Text = "Thêm";
            this.btnThemDTQ.UseVisualStyleBackColor = false;
            this.btnThemDTQ.FlatStyle = FlatStyle.Flat;
            this.btnThemDTQ.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnThemDTQ.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.tabDanhMucPage3.Controls.Add(this.btnThemDTQ);
            this.btnThemDTQ.Click += btnThemDTQ_Click;
            this.btnDong = new Button();
            this.btnDong.Name = "btnDong";
            this.btnDong.SetBounds(1164,525,146,30);
            this.btnDong.Text = "Đóng";
            this.btnDong.UseVisualStyleBackColor = false;
            this.btnDong.FlatStyle = FlatStyle.Flat;
            this.btnDong.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnDong.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.Controls.Add(this.btnDong);
            this.btnDong.Click += btnDong_Click;
            this.btnDong.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            this.Load += FrmDanhMuc_Load;
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
