using System;
using System.Windows.Forms;

namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmDangKyDoan
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing) { if (disposing && components != null) components.Dispose(); base.Dispose(disposing); }
        private GroupBox grpDoan;
        private Label label1;
        private TextBox txtMaDoan;
        private Label label2;
        private TextBox txtTenCQ;
        private Label label3;
        private TextBox txtDiaChi;
        private Label label4;
        private TextBox txtDT;
        private Label label5;
        private TextBox txtDaiDien;
        private GroupBox grpDangKy;
        private Label label6;
        private TextBox txtSo;
        private Label label7;
        private ComboBox cboTour;
        private Label label8;
        private DateTimePicker dtDi;
        private Label label9;
        private NumericUpDown numNguoi;
        private Label label10;
        private TextBox txtDon;
        private Label label11;
        private NumericUpDown numCoc;
        private CheckBox chkBH;
        private Label label12;
        private Label lblKetThuc;
        private Label label14;
        private Label lblTong;
        private Label label16;
        private DataGridView dgvThanhVien;
        private Button btnDangKy;
        private Button btnHuy;
        private Label label17;
        private DataGridView dgv;
        private Button btnDong;
        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F,96F);
            this.AutoScaleMode = AutoScaleMode.Dpi;
            this.ClientSize = new System.Drawing.Size(1340,688);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Text = "Phiếu đăng ký theo đoàn";
            this.Name = "FrmDangKyDoan";
            this.StartPosition = FormStartPosition.CenterParent;
            this.BackColor = System.Drawing.SystemColors.Control;
            this.MinimumSize = new System.Drawing.Size(1356,727);
            this.grpDoan = new GroupBox();
            this.grpDoan.Name = "grpDoan";
            this.grpDoan.SetBounds(26,12,633,212);
            this.grpDoan.Text = "Thông tin đoàn khách";
            this.Controls.Add(this.grpDoan);
            this.label1 = new Label();
            this.label1.Name = "label1";
            this.label1.SetBounds(13,28,139,24);
            this.label1.Text = "Mã đoàn:";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.grpDoan.Controls.Add(this.label1);
            this.txtMaDoan = new TextBox();
            this.txtMaDoan.Name = "txtMaDoan";
            this.txtMaDoan.SetBounds(158,28,158,24);
            this.txtMaDoan.MaxLength = 1000;
            this.grpDoan.Controls.Add(this.txtMaDoan);
            this.label2 = new Label();
            this.label2.Name = "label2";
            this.label2.SetBounds(13,63,139,24);
            this.label2.Text = "Cơ quan / gia đình:";
            this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.grpDoan.Controls.Add(this.label2);
            this.txtTenCQ = new TextBox();
            this.txtTenCQ.Name = "txtTenCQ";
            this.txtTenCQ.SetBounds(158,63,462,24);
            this.txtTenCQ.MaxLength = 1000;
            this.grpDoan.Controls.Add(this.txtTenCQ);
            this.label3 = new Label();
            this.label3.Name = "label3";
            this.label3.SetBounds(13,98,139,24);
            this.label3.Text = "Địa chỉ:";
            this.label3.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.grpDoan.Controls.Add(this.label3);
            this.txtDiaChi = new TextBox();
            this.txtDiaChi.Name = "txtDiaChi";
            this.txtDiaChi.SetBounds(158,98,462,24);
            this.txtDiaChi.MaxLength = 1000;
            this.grpDoan.Controls.Add(this.txtDiaChi);
            this.label4 = new Label();
            this.label4.Name = "label4";
            this.label4.SetBounds(13,133,139,24);
            this.label4.Text = "Điện thoại:";
            this.label4.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.grpDoan.Controls.Add(this.label4);
            this.txtDT = new TextBox();
            this.txtDT.Name = "txtDT";
            this.txtDT.SetBounds(158,133,198,24);
            this.txtDT.MaxLength = 1000;
            this.grpDoan.Controls.Add(this.txtDT);
            this.label5 = new Label();
            this.label5.Name = "label5";
            this.label5.SetBounds(13,168,139,24);
            this.label5.Text = "Người đại diện:";
            this.label5.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.grpDoan.Controls.Add(this.label5);
            this.txtDaiDien = new TextBox();
            this.txtDaiDien.Name = "txtDaiDien";
            this.txtDaiDien.SetBounds(158,168,462,24);
            this.txtDaiDien.MaxLength = 1000;
            this.grpDoan.Controls.Add(this.txtDaiDien);
            this.grpDangKy = new GroupBox();
            this.grpDangKy.Name = "grpDangKy";
            this.grpDangKy.SetBounds(675,12,638,212);
            this.grpDangKy.Text = "Đăng ký tour";
            this.Controls.Add(this.grpDangKy);
            this.label6 = new Label();
            this.label6.Name = "label6";
            this.label6.SetBounds(13,28,113,24);
            this.label6.Text = "Số phiếu:";
            this.label6.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.grpDangKy.Controls.Add(this.label6);
            this.txtSo = new TextBox();
            this.txtSo.Name = "txtSo";
            this.txtSo.SetBounds(138,28,158,24);
            this.txtSo.MaxLength = 1000;
            this.grpDangKy.Controls.Add(this.txtSo);
            this.label7 = new Label();
            this.label7.Name = "label7";
            this.label7.SetBounds(317,28,47,24);
            this.label7.Text = "Tour:";
            this.label7.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.grpDangKy.Controls.Add(this.label7);
            this.cboTour = new ComboBox();
            this.cboTour.Name = "cboTour";
            this.cboTour.SetBounds(369,28,253,24);
            this.cboTour.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboTour.DropDownWidth = 600;
            this.grpDangKy.Controls.Add(this.cboTour);
            this.cboTour.SelectedIndexChanged += TinhTong;
            this.label8 = new Label();
            this.label8.Name = "label8";
            this.label8.SetBounds(13,63,113,24);
            this.label8.Text = "Ngày đi:";
            this.label8.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.grpDangKy.Controls.Add(this.label8);
            this.dtDi = new DateTimePicker();
            this.dtDi.Name = "dtDi";
            this.dtDi.SetBounds(138,63,158,24);
            this.dtDi.Format = DateTimePickerFormat.Custom;
            this.dtDi.CustomFormat = "dd/MM/yyyy";
            this.grpDangKy.Controls.Add(this.dtDi);
            this.dtDi.ValueChanged += TinhTong;
            this.label9 = new Label();
            this.label9.Name = "label9";
            this.label9.SetBounds(317,63,80,24);
            this.label9.Text = "Số người:";
            this.label9.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.grpDangKy.Controls.Add(this.label9);
            this.numNguoi = new NumericUpDown();
            this.numNguoi.Name = "numNguoi";
            this.numNguoi.SetBounds(402,63,106,24);
            this.numNguoi.Minimum = 13M;
            this.numNguoi.Maximum = 10000M;
            this.numNguoi.Value = 13M;
            this.numNguoi.TextAlign = HorizontalAlignment.Right;
            this.grpDangKy.Controls.Add(this.numNguoi);
            this.numNguoi.ValueChanged += TinhTong;
            this.label10 = new Label();
            this.label10.Name = "label10";
            this.label10.SetBounds(13,98,119,24);
            this.label10.Text = "Địa điểm đón:";
            this.label10.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.grpDangKy.Controls.Add(this.label10);
            this.txtDon = new TextBox();
            this.txtDon.Name = "txtDon";
            this.txtDon.SetBounds(138,98,484,24);
            this.txtDon.MaxLength = 1000;
            this.grpDangKy.Controls.Add(this.txtDon);
            this.label11 = new Label();
            this.label11.Name = "label11";
            this.label11.SetBounds(13,133,113,24);
            this.label11.Text = "Tiền cọc:";
            this.label11.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.grpDangKy.Controls.Add(this.label11);
            this.numCoc = new NumericUpDown();
            this.numCoc.Name = "numCoc";
            this.numCoc.SetBounds(138,133,185,24);
            this.numCoc.Minimum = 0M;
            this.numCoc.Maximum = 100000000000M;
            this.numCoc.Value = 10000000M;
            this.numCoc.TextAlign = HorizontalAlignment.Right;
            this.numCoc.ThousandsSeparator = true;
            this.numCoc.Increment = 100000M;
            this.grpDangKy.Controls.Add(this.numCoc);
            this.chkBH = new CheckBox();
            this.chkBH.Name = "chkBH";
            this.chkBH.SetBounds(343,133,211,25);
            this.chkBH.Text = "Mua bảo hiểm";
            this.grpDangKy.Controls.Add(this.chkBH);
            this.chkBH.CheckedChanged += chkBH_CheckedChanged;
            this.label12 = new Label();
            this.label12.Name = "label12";
            this.label12.SetBounds(13,168,113,24);
            this.label12.Text = "Kết thúc DK:";
            this.label12.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.grpDangKy.Controls.Add(this.label12);
            this.lblKetThuc = new Label();
            this.lblKetThuc.Name = "lblKetThuc";
            this.lblKetThuc.SetBounds(138,168,145,24);
            this.lblKetThuc.Text = "-";
            this.lblKetThuc.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblKetThuc.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.grpDangKy.Controls.Add(this.lblKetThuc);
            this.label14 = new Label();
            this.label14.Name = "label14";
            this.label14.SetBounds(290,168,139,24);
            this.label14.Text = "Tổng dự kiến:";
            this.label14.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.label14.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.grpDangKy.Controls.Add(this.label14);
            this.lblTong = new Label();
            this.lblTong.Name = "lblTong";
            this.lblTong.SetBounds(435,168,187,24);
            this.lblTong.Text = "0 đ";
            this.lblTong.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblTong.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.lblTong.ForeColor = System.Drawing.Color.DarkRed;
            this.grpDangKy.Controls.Add(this.lblTong);
            this.label16 = new Label();
            this.label16.Name = "label16";
            this.label16.SetBounds(26,230,1181,24);
            this.label16.Text = "Danh sách người cùng đi (bắt buộc đủ số người khi mua bảo hiểm):";
            this.label16.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.label16);
            this.dgvThanhVien = new DataGridView();
            this.dgvThanhVien.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            this.dgvThanhVien.Name = "dgvThanhVien";
            this.dgvThanhVien.SetBounds(26,255,1287,150);
            this.dgvThanhVien.BackgroundColor = System.Drawing.Color.White;
            this.dgvThanhVien.GridColor = System.Drawing.Color.FromArgb(220,220,220);
            this.dgvThanhVien.BorderStyle = BorderStyle.FixedSingle;
            this.dgvThanhVien.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
            this.dgvThanhVien.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvThanhVien.MultiSelect = false;
            this.dgvThanhVien.ReadOnly = false;
            this.dgvThanhVien.AllowUserToAddRows = true;
            this.dgvThanhVien.AllowUserToDeleteRows = true;
            this.dgvThanhVien.RowHeadersWidth = 30;
            this.dgvThanhVien.RowTemplate.Height = 25;
            this.dgvThanhVien.ColumnHeadersHeight = 25;
            this.dgvThanhVien.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.dgvThanhVien.EnableHeadersVisualStyles = false;
            this.dgvThanhVien.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.SystemColors.Control;
            this.dgvThanhVien.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(205,232,255);
            this.dgvThanhVien.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgvThanhVien.DefaultCellStyle.NullValue = "";
            this.dgvThanhVien.DefaultCellStyle.Format = "";
            this.Controls.Add(this.dgvThanhVien);
            this.dgvThanhVien.DataBindingComplete += FormHelper.DinhDangBang;
            this.dgvThanhVien.SizeChanged += FormHelper.KichThuocBangThayDoi;
            this.dgvThanhVien.CellValueChanged += FormHelper.DuLieuOThayDoi;
            this.dgvThanhVien.DataError += FormHelper.LoiNhapBang;
            this.btnDangKy = new Button();
            this.btnDangKy.Name = "btnDangKy";
            this.btnDangKy.SetBounds(868,415,211,34);
            this.btnDangKy.Text = "Lập phiếu đăng ký";
            this.btnDangKy.UseVisualStyleBackColor = false;
            this.btnDangKy.FlatStyle = FlatStyle.Flat;
            this.btnDangKy.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnDangKy.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.Controls.Add(this.btnDangKy);
            this.btnDangKy.Click += btnDangKy_Click;
            this.btnHuy = new Button();
            this.btnHuy.Name = "btnHuy";
            this.btnHuy.SetBounds(1092,415,222,34);
            this.btnHuy.Text = "Hủy phiếu (mất cọc)";
            this.btnHuy.UseVisualStyleBackColor = false;
            this.btnHuy.FlatStyle = FlatStyle.Flat;
            this.btnHuy.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnHuy.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.Controls.Add(this.btnHuy);
            this.btnHuy.Click += btnHuy_Click;
            this.label17 = new Label();
            this.label17.Name = "label17";
            this.label17.SetBounds(26,451,653,24);
            this.label17.Text = "Các phiếu đăng ký đoàn:";
            this.label17.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.label17);
            this.dgv = new DataGridView();
            this.dgv.Name = "dgv";
            this.dgv.SetBounds(26,478,1287,163);
            this.dgv.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            this.dgv.BackgroundColor = System.Drawing.Color.White;
            this.dgv.GridColor = System.Drawing.Color.FromArgb(220,220,220);
            this.dgv.BorderStyle = BorderStyle.FixedSingle;
            this.dgv.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
            this.dgv.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgv.MultiSelect = false;
            this.dgv.ReadOnly = true;
            this.dgv.AllowUserToAddRows = false;
            this.dgv.AllowUserToDeleteRows = false;
            this.dgv.RowHeadersWidth = 30;
            this.dgv.RowTemplate.Height = 25;
            this.dgv.ColumnHeadersHeight = 25;
            this.dgv.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.dgv.EnableHeadersVisualStyles = false;
            this.dgv.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.SystemColors.Control;
            this.dgv.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(205,232,255);
            this.dgv.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgv.DefaultCellStyle.NullValue = "";
            this.dgv.DefaultCellStyle.Format = "";
            this.Controls.Add(this.dgv);
            this.dgv.DataBindingComplete += FormHelper.DinhDangBang;
            this.dgv.SizeChanged += FormHelper.KichThuocBangThayDoi;
            this.dgv.CellValueChanged += FormHelper.DuLieuOThayDoi;
            this.btnDong = new Button();
            this.btnDong.Name = "btnDong";
            this.btnDong.SetBounds(1182,645,132,30);
            this.btnDong.Text = "Đóng";
            this.btnDong.UseVisualStyleBackColor = false;
            this.btnDong.FlatStyle = FlatStyle.Flat;
            this.btnDong.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnDong.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.Controls.Add(this.btnDong);
            this.btnDong.Click += btnDong_Click;
            this.btnDong.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            this.Load += FrmDangKyDoan_Load;
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
