using System;
using System.Windows.Forms;

namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmDangKyLe
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing) { if (disposing && components != null) components.Dispose(); base.Dispose(disposing); }
        private Label label1;
        private TextBox txtSo;
        private Label label2;
        private ComboBox cboChuyen;
        private Label label3;
        private ComboBox cboDiemBan;
        private Label label4;
        private TextBox txtTen;
        private Label label5;
        private TextBox txtDT;
        private Label label6;
        private NumericUpDown numNguoi;
        private Label label7;
        private Label lblThanhTien;
        private Button btnDangKy;
        private DataGridView dgv;
        private Button btnDong;
        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F,96F);
            this.AutoScaleMode = AutoScaleMode.Dpi;
            this.ClientSize = new System.Drawing.Size(1340,548);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Text = "Đăng ký khách lẻ theo chuyến";
            this.Name = "FrmDangKyLe";
            this.StartPosition = FormStartPosition.CenterParent;
            this.BackColor = System.Drawing.SystemColors.Control;
            this.MinimumSize = new System.Drawing.Size(1356,587);
            this.label1 = new Label();
            this.label1.Name = "label1";
            this.label1.SetBounds(32,18,124,24);
            this.label1.Text = "Số đăng ký:";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.label1);
            this.txtSo = new TextBox();
            this.txtSo.Name = "txtSo";
            this.txtSo.SetBounds(157,18,190,24);
            this.txtSo.MaxLength = 1000;
            this.Controls.Add(this.txtSo);
            this.label2 = new Label();
            this.label2.Name = "label2";
            this.label2.SetBounds(391,18,80,24);
            this.label2.Text = "Chuyến:";
            this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.label2);
            this.cboChuyen = new ComboBox();
            this.cboChuyen.Name = "cboChuyen";
            this.cboChuyen.SetBounds(471,18,512,24);
            this.cboChuyen.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboChuyen.DropDownWidth = 600;
            this.Controls.Add(this.cboChuyen);
            this.cboChuyen.SelectedIndexChanged += TinhTien;
            this.label3 = new Label();
            this.label3.Name = "label3";
            this.label3.SetBounds(32,53,124,24);
            this.label3.Text = "Điểm bán vé:";
            this.label3.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.label3);
            this.cboDiemBan = new ComboBox();
            this.cboDiemBan.Name = "cboDiemBan";
            this.cboDiemBan.SetBounds(157,53,278,24);
            this.cboDiemBan.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboDiemBan.DropDownWidth = 600;
            this.Controls.Add(this.cboDiemBan);
            this.label4 = new Label();
            this.label4.Name = "label4";
            this.label4.SetBounds(478,53,139,24);
            this.label4.Text = "Người đăng ký:";
            this.label4.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.label4);
            this.txtTen = new TextBox();
            this.txtTen.Name = "txtTen";
            this.txtTen.SetBounds(617,53,293,24);
            this.txtTen.MaxLength = 1000;
            this.Controls.Add(this.txtTen);
            this.label5 = new Label();
            this.label5.Name = "label5";
            this.label5.SetBounds(961,53,102,24);
            this.label5.Text = "Điện thoại:";
            this.label5.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.label5);
            this.txtDT = new TextBox();
            this.txtDT.Name = "txtDT";
            this.txtDT.SetBounds(1064,53,190,24);
            this.txtDT.MaxLength = 1000;
            this.Controls.Add(this.txtDT);
            this.label6 = new Label();
            this.label6.Name = "label6";
            this.label6.SetBounds(32,88,124,24);
            this.label6.Text = "Số người:";
            this.label6.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.label6);
            this.numNguoi = new NumericUpDown();
            this.numNguoi.Name = "numNguoi";
            this.numNguoi.SetBounds(157,88,102,24);
            this.numNguoi.Minimum = 1M;
            this.numNguoi.Maximum = 11M;
            this.numNguoi.Value = 1M;
            this.numNguoi.TextAlign = HorizontalAlignment.Right;
            this.Controls.Add(this.numNguoi);
            this.numNguoi.ValueChanged += TinhTien;
            this.label7 = new Label();
            this.label7.Name = "label7";
            this.label7.SetBounds(303,88,132,24);
            this.label7.Text = "Thành tiền:";
            this.label7.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.label7.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.Controls.Add(this.label7);
            this.lblThanhTien = new Label();
            this.lblThanhTien.Name = "lblThanhTien";
            this.lblThanhTien.SetBounds(434,88,322,24);
            this.lblThanhTien.Text = "0 đ";
            this.lblThanhTien.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblThanhTien.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.lblThanhTien.ForeColor = System.Drawing.Color.DarkRed;
            this.Controls.Add(this.lblThanhTien);
            this.btnDangKy = new Button();
            this.btnDangKy.Name = "btnDangKy";
            this.btnDangKy.SetBounds(961,85,344,34);
            this.btnDangKy.Text = "Đăng ký và thanh toán vé";
            this.btnDangKy.UseVisualStyleBackColor = false;
            this.btnDangKy.FlatStyle = FlatStyle.Flat;
            this.btnDangKy.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnDangKy.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.Controls.Add(this.btnDangKy);
            this.btnDangKy.Click += btnDangKy_Click;
            this.dgv = new DataGridView();
            this.dgv.Name = "dgv";
            this.dgv.SetBounds(32,133,1273,350);
            this.dgv.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            this.dgv.BackgroundColor = System.Drawing.Color.White;
            this.dgv.GridColor = System.Drawing.Color.FromArgb(220,220,220);
            this.dgv.BorderStyle = BorderStyle.FixedSingle;
            this.dgv.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
            this.dgv.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgv.MultiSelect = false;
            this.dgv.ReadOnly = true;
            this.dgv.AllowUserToAddRows = false;
            this.dgv.AllowUserToDeleteRows = false;
            this.dgv.RowHeadersWidth = 30;
            this.dgv.RowTemplate.Height = 25;
            this.dgv.ColumnHeadersHeight = 25;
            this.dgv.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.dgv.EnableHeadersVisualStyles = false;
            this.dgv.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.SystemColors.Control;
            this.dgv.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(205,232,255);
            this.dgv.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgv.DefaultCellStyle.NullValue = "";
            this.dgv.DefaultCellStyle.Format = "";
            this.Controls.Add(this.dgv);
            this.dgv.DataBindingComplete += FormHelper.DinhDangBang;
            this.dgv.SizeChanged += FormHelper.KichThuocBangThayDoi;
            this.dgv.CellValueChanged += FormHelper.DuLieuOThayDoi;
            this.btnDong = new Button();
            this.btnDong.Name = "btnDong";
            this.btnDong.SetBounds(1164,505,146,30);
            this.btnDong.Text = "Đóng";
            this.btnDong.UseVisualStyleBackColor = false;
            this.btnDong.FlatStyle = FlatStyle.Flat;
            this.btnDong.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnDong.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.Controls.Add(this.btnDong);
            this.btnDong.Click += btnDong_Click;
            this.btnDong.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            this.Load += FrmDangKyLe_Load;
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
