using System;
using System.Windows.Forms;

namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmKetThucKhaoSat
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing) { if (disposing && components != null) components.Dispose(); base.Dispose(disposing); }
        private TabControl tabKT;
        private TabPage tabKTPage0;
        private TabPage tabKTPage1;
        private DataGridView dgvDoan;
        private Label label1;
        private TextBox txtSoTT;
        private Label label2;
        private TextBox txtSoDK;
        private Label label3;
        private DateTimePicker dtTT;
        private Label label4;
        private NumericUpDown numTien;
        private Label label5;
        private TextBox txtGhiChu;
        private Button btnThanhToan;
        private Label label6;
        private ComboBox cboLoaiKS;
        private Label label7;
        private ComboBox cboDangKy;
        private Label label8;
        private TextBox txtMaKS;
        private Label label9;
        private DateTimePicker dtGui;
        private Button btnGui;
        private DataGridView dgvKS;
        private Label label10;
        private TextBox txtKSChon;
        private Label label11;
        private DateTimePicker dtPH;
        private Label label12;
        private NumericUpDown numDiem;
        private Label label13;
        private TextBox txtGopY;
        private Button btnGhiPH;
        private Button btnDong;
        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F,96F);
            this.AutoScaleMode = AutoScaleMode.Dpi;
            this.ClientSize = new System.Drawing.Size(1340,608);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Text = "Kết thúc tour - thanh toán đoàn - khảo sát";
            this.Name = "FrmKetThucKhaoSat";
            this.StartPosition = FormStartPosition.CenterParent;
            this.BackColor = System.Drawing.SystemColors.Control;
            this.MinimumSize = new System.Drawing.Size(1356,647);
            this.tabKT = new TabControl();
            this.tabKT.Name = "tabKT";
            this.tabKT.SetBounds(28,16,1285,537);
            this.tabKT.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            this.Controls.Add(this.tabKT);
            this.tabKTPage0 = new TabPage();
            this.tabKTPage0.Name = "tabKTPage0";
            this.tabKTPage0.SetBounds(0,0,1273,512);
            this.tabKTPage0.Text = "Thanh toán sau tour (đoàn)";
            this.tabKTPage0.BackColor = System.Drawing.Color.White;
            this.tabKT.Controls.Add(this.tabKTPage0);
            this.tabKTPage1 = new TabPage();
            this.tabKTPage1.Name = "tabKTPage1";
            this.tabKTPage1.SetBounds(0,0,1273,512);
            this.tabKTPage1.Text = "Khảo sát khách hàng";
            this.tabKTPage1.BackColor = System.Drawing.Color.White;
            this.tabKT.Controls.Add(this.tabKTPage1);
            this.dgvDoan = new DataGridView();
            this.dgvDoan.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            this.dgvDoan.Name = "dgvDoan";
            this.dgvDoan.SetBounds(14,10,1248,320);
            this.dgvDoan.BackgroundColor = System.Drawing.Color.White;
            this.dgvDoan.GridColor = System.Drawing.Color.FromArgb(220,220,220);
            this.dgvDoan.BorderStyle = BorderStyle.FixedSingle;
            this.dgvDoan.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
            this.dgvDoan.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvDoan.MultiSelect = false;
            this.dgvDoan.ReadOnly = true;
            this.dgvDoan.AllowUserToAddRows = false;
            this.dgvDoan.AllowUserToDeleteRows = false;
            this.dgvDoan.RowHeadersWidth = 30;
            this.dgvDoan.RowTemplate.Height = 25;
            this.dgvDoan.ColumnHeadersHeight = 25;
            this.dgvDoan.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.dgvDoan.EnableHeadersVisualStyles = false;
            this.dgvDoan.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.SystemColors.Control;
            this.dgvDoan.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(205,232,255);
            this.dgvDoan.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgvDoan.DefaultCellStyle.NullValue = "";
            this.dgvDoan.DefaultCellStyle.Format = "";
            this.tabKTPage0.Controls.Add(this.dgvDoan);
            this.dgvDoan.DataBindingComplete += FormHelper.DinhDangBang;
            this.dgvDoan.SizeChanged += FormHelper.KichThuocBangThayDoi;
            this.dgvDoan.CellValueChanged += FormHelper.DuLieuOThayDoi;
            this.dgvDoan.SelectionChanged += dgvDoan_SelectionChanged;
            this.label1 = new Label();
            this.label1.Name = "label1";
            this.label1.SetBounds(17,347,126,24);
            this.label1.Text = "Số thanh toán:";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabKTPage0.Controls.Add(this.label1);
            this.txtSoTT = new TextBox();
            this.txtSoTT.Name = "txtSoTT";
            this.txtSoTT.SetBounds(148,347,166,24);
            this.txtSoTT.MaxLength = 1000;
            this.tabKTPage0.Controls.Add(this.txtSoTT);
            this.label2 = new Label();
            this.label2.Name = "label2";
            this.label2.SetBounds(350,347,105,24);
            this.label2.Text = "Phiếu đoàn:";
            this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabKTPage0.Controls.Add(this.label2);
            this.txtSoDK = new TextBox();
            this.txtSoDK.Name = "txtSoDK";
            this.txtSoDK.SetBounds(461,347,166,24);
            this.txtSoDK.MaxLength = 1000;
            this.txtSoDK.ReadOnly = true;
            this.tabKTPage0.Controls.Add(this.txtSoDK);
            this.label3 = new Label();
            this.label3.Name = "label3";
            this.label3.SetBounds(669,347,147,24);
            this.label3.Text = "Ngày thanh toán:";
            this.label3.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabKTPage0.Controls.Add(this.label3);
            this.dtTT = new DateTimePicker();
            this.dtTT.Name = "dtTT";
            this.dtTT.SetBounds(821,347,166,24);
            this.dtTT.Format = DateTimePickerFormat.Custom;
            this.dtTT.CustomFormat = "dd/MM/yyyy";
            this.tabKTPage0.Controls.Add(this.dtTT);
            this.label4 = new Label();
            this.label4.Name = "label4";
            this.label4.SetBounds(17,382,126,24);
            this.label4.Text = "Số tiền:";
            this.label4.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabKTPage0.Controls.Add(this.label4);
            this.numTien = new NumericUpDown();
            this.numTien.Name = "numTien";
            this.numTien.SetBounds(148,382,208,24);
            this.numTien.Minimum = 0M;
            this.numTien.Maximum = 100000000000M;
            this.numTien.Value = 0M;
            this.numTien.TextAlign = HorizontalAlignment.Right;
            this.numTien.ThousandsSeparator = true;
            this.numTien.Increment = 100000M;
            this.tabKTPage0.Controls.Add(this.numTien);
            this.label5 = new Label();
            this.label5.Name = "label5";
            this.label5.SetBounds(391,382,77,24);
            this.label5.Text = "Ghi chú:";
            this.label5.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabKTPage0.Controls.Add(this.label5);
            this.txtGhiChu = new TextBox();
            this.txtGhiChu.Name = "txtGhiChu";
            this.txtGhiChu.SetBounds(474,382,444,24);
            this.txtGhiChu.MaxLength = 1000;
            this.tabKTPage0.Controls.Add(this.txtGhiChu);
            this.btnThanhToan = new Button();
            this.btnThanhToan.Name = "btnThanhToan";
            this.btnThanhToan.SetBounds(1057,379,194,32);
            this.btnThanhToan.Text = "Ghi nhận thanh toán";
            this.btnThanhToan.UseVisualStyleBackColor = false;
            this.btnThanhToan.FlatStyle = FlatStyle.Flat;
            this.btnThanhToan.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnThanhToan.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.tabKTPage0.Controls.Add(this.btnThanhToan);
            this.btnThanhToan.Click += btnThanhToan_Click;
            this.label6 = new Label();
            this.label6.Name = "label6";
            this.label6.SetBounds(17,14,98,24);
            this.label6.Text = "Loại khách:";
            this.label6.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabKTPage1.Controls.Add(this.label6);
            this.cboLoaiKS = new ComboBox();
            this.cboLoaiKS.Name = "cboLoaiKS";
            this.cboLoaiKS.SetBounds(121,14,111,24);
            this.cboLoaiKS.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboLoaiKS.DropDownWidth = 600;
            this.tabKTPage1.Controls.Add(this.cboLoaiKS);
            this.cboLoaiKS.SelectedIndexChanged += cboLoaiKS_SelectedIndexChanged;
            this.label7 = new Label();
            this.label7.Name = "label7";
            this.label7.SetBounds(259,14,174,24);
            this.label7.Text = "Đăng ký đã kết thúc:";
            this.label7.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabKTPage1.Controls.Add(this.label7);
            this.cboDangKy = new ComboBox();
            this.cboDangKy.Name = "cboDangKy";
            this.cboDangKy.SetBounds(440,14,361,24);
            this.cboDangKy.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboDangKy.DropDownWidth = 600;
            this.tabKTPage1.Controls.Add(this.cboDangKy);
            this.label8 = new Label();
            this.label8.Name = "label8";
            this.label8.SetBounds(835,14,63,24);
            this.label8.Text = "Mã KS:";
            this.label8.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabKTPage1.Controls.Add(this.label8);
            this.txtMaKS = new TextBox();
            this.txtMaKS.Name = "txtMaKS";
            this.txtMaKS.SetBounds(904,14,125,24);
            this.txtMaKS.MaxLength = 1000;
            this.tabKTPage1.Controls.Add(this.txtMaKS);
            this.label9 = new Label();
            this.label9.Name = "label9";
            this.label9.SetBounds(17,49,98,24);
            this.label9.Text = "Ngày gửi:";
            this.label9.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabKTPage1.Controls.Add(this.label9);
            this.dtGui = new DateTimePicker();
            this.dtGui.Name = "dtGui";
            this.dtGui.SetBounds(121,49,166,24);
            this.dtGui.Format = DateTimePickerFormat.Custom;
            this.dtGui.CustomFormat = "dd/MM/yyyy";
            this.tabKTPage1.Controls.Add(this.dtGui);
            this.btnGui = new Button();
            this.btnGui.Name = "btnGui";
            this.btnGui.SetBounds(1057,46,194,32);
            this.btnGui.Text = "Gửi phiếu khảo sát";
            this.btnGui.UseVisualStyleBackColor = false;
            this.btnGui.FlatStyle = FlatStyle.Flat;
            this.btnGui.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnGui.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.tabKTPage1.Controls.Add(this.btnGui);
            this.btnGui.Click += btnGui_Click;
            this.dgvKS = new DataGridView();
            this.dgvKS.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            this.dgvKS.Name = "dgvKS";
            this.dgvKS.SetBounds(14,87,1248,260);
            this.dgvKS.BackgroundColor = System.Drawing.Color.White;
            this.dgvKS.GridColor = System.Drawing.Color.FromArgb(220,220,220);
            this.dgvKS.BorderStyle = BorderStyle.FixedSingle;
            this.dgvKS.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
            this.dgvKS.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvKS.MultiSelect = false;
            this.dgvKS.ReadOnly = true;
            this.dgvKS.AllowUserToAddRows = false;
            this.dgvKS.AllowUserToDeleteRows = false;
            this.dgvKS.RowHeadersWidth = 30;
            this.dgvKS.RowTemplate.Height = 25;
            this.dgvKS.ColumnHeadersHeight = 25;
            this.dgvKS.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.dgvKS.EnableHeadersVisualStyles = false;
            this.dgvKS.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.SystemColors.Control;
            this.dgvKS.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(205,232,255);
            this.dgvKS.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgvKS.DefaultCellStyle.NullValue = "";
            this.dgvKS.DefaultCellStyle.Format = "";
            this.tabKTPage1.Controls.Add(this.dgvKS);
            this.dgvKS.DataBindingComplete += FormHelper.DinhDangBang;
            this.dgvKS.SizeChanged += FormHelper.KichThuocBangThayDoi;
            this.dgvKS.CellValueChanged += FormHelper.DuLieuOThayDoi;
            this.dgvKS.SelectionChanged += dgvKS_SelectionChanged;
            this.label10 = new Label();
            this.label10.Name = "label10";
            this.label10.SetBounds(17,362,105,24);
            this.label10.Text = "Phiếu chọn:";
            this.label10.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabKTPage1.Controls.Add(this.label10);
            this.txtKSChon = new TextBox();
            this.txtKSChon.Name = "txtKSChon";
            this.txtKSChon.SetBounds(128,362,139,24);
            this.txtKSChon.MaxLength = 1000;
            this.txtKSChon.ReadOnly = true;
            this.tabKTPage1.Controls.Add(this.txtKSChon);
            this.label11 = new Label();
            this.label11.Name = "label11";
            this.label11.SetBounds(294,362,126,24);
            this.label11.Text = "Ngày phản hồi:";
            this.label11.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabKTPage1.Controls.Add(this.label11);
            this.dtPH = new DateTimePicker();
            this.dtPH.Name = "dtPH";
            this.dtPH.SetBounds(426,362,166,24);
            this.dtPH.Format = DateTimePickerFormat.Custom;
            this.dtPH.CustomFormat = "dd/MM/yyyy";
            this.tabKTPage1.Controls.Add(this.dtPH);
            this.label12 = new Label();
            this.label12.Name = "label12";
            this.label12.SetBounds(627,362,105,24);
            this.label12.Text = "Điểm (1-5):";
            this.label12.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabKTPage1.Controls.Add(this.label12);
            this.numDiem = new NumericUpDown();
            this.numDiem.Name = "numDiem";
            this.numDiem.SetBounds(738,362,83,24);
            this.numDiem.Minimum = 1M;
            this.numDiem.Maximum = 5M;
            this.numDiem.Value = 5M;
            this.numDiem.TextAlign = HorizontalAlignment.Right;
            this.tabKTPage1.Controls.Add(this.numDiem);
            this.label13 = new Label();
            this.label13.Name = "label13";
            this.label13.SetBounds(17,397,105,24);
            this.label13.Text = "Góp ý:";
            this.label13.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabKTPage1.Controls.Add(this.label13);
            this.txtGopY = new TextBox();
            this.txtGopY.Name = "txtGopY";
            this.txtGopY.SetBounds(128,397,902,24);
            this.txtGopY.MaxLength = 1000;
            this.tabKTPage1.Controls.Add(this.txtGopY);
            this.btnGhiPH = new Button();
            this.btnGhiPH.Name = "btnGhiPH";
            this.btnGhiPH.SetBounds(1057,394,194,32);
            this.btnGhiPH.Text = "Ghi nhận góp ý";
            this.btnGhiPH.UseVisualStyleBackColor = false;
            this.btnGhiPH.FlatStyle = FlatStyle.Flat;
            this.btnGhiPH.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnGhiPH.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.tabKTPage1.Controls.Add(this.btnGhiPH);
            this.btnGhiPH.Click += btnGhiPH_Click;
            this.btnDong = new Button();
            this.btnDong.Name = "btnDong";
            this.btnDong.SetBounds(1174,565,139,30);
            this.btnDong.Text = "Đóng";
            this.btnDong.UseVisualStyleBackColor = false;
            this.btnDong.FlatStyle = FlatStyle.Flat;
            this.btnDong.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnDong.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.Controls.Add(this.btnDong);
            this.btnDong.Click += btnDong_Click;
            this.btnDong.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            this.Load += FrmKetThucKhaoSat_Load;
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
