using System;
using System.Windows.Forms;

namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmLuongThongKe
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing) { if (disposing && components != null) components.Dispose(); base.Dispose(disposing); }
        private TabControl tabTK;
        private TabPage tabTKPage0;
        private TabPage tabTKPage1;
        private Label label1;
        private NumericUpDown numThang;
        private Label label2;
        private NumericUpDown numNam;
        private Button btnLuong;
        private Label label3;
        private DataGridView dgvLuong;
        private Label label4;
        private DateTimePicker dtTu;
        private Label label5;
        private DateTimePicker dtDen;
        private Button btnTongHop;
        private DataGridView dgvTongHop;
        private Button btnDong;
        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F,96F);
            this.AutoScaleMode = AutoScaleMode.Dpi;
            this.ClientSize = new System.Drawing.Size(1340,548);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Text = "Lương hướng dẫn viên - thống kê";
            this.Name = "FrmLuongThongKe";
            this.StartPosition = FormStartPosition.CenterParent;
            this.BackColor = System.Drawing.SystemColors.Control;
            this.MinimumSize = new System.Drawing.Size(1356,587);
            this.tabTK = new TabControl();
            this.tabTK.Name = "tabTK";
            this.tabTK.SetBounds(29,16,1281,477);
            this.tabTK.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            this.Controls.Add(this.tabTK);
            this.tabTKPage0 = new TabPage();
            this.tabTKPage0.Name = "tabTKPage0";
            this.tabTKPage0.SetBounds(0,0,1270,452);
            this.tabTKPage0.Text = "Lương hướng dẫn viên";
            this.tabTKPage0.BackColor = System.Drawing.Color.White;
            this.tabTK.Controls.Add(this.tabTKPage0);
            this.tabTKPage1 = new TabPage();
            this.tabTKPage1.Name = "tabTKPage1";
            this.tabTKPage1.SetBounds(0,0,1270,452);
            this.tabTKPage1.Text = "Thống kê tổng hợp";
            this.tabTKPage1.BackColor = System.Drawing.Color.White;
            this.tabTK.Controls.Add(this.tabTKPage1);
            this.label1 = new Label();
            this.label1.Name = "label1";
            this.label1.SetBounds(18,14,67,24);
            this.label1.Text = "Tháng:";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabTKPage0.Controls.Add(this.label1);
            this.numThang = new NumericUpDown();
            this.numThang.Name = "numThang";
            this.numThang.SetBounds(91,14,88,24);
            this.numThang.Minimum = 1M;
            this.numThang.Maximum = 12M;
            this.numThang.Value = 9M;
            this.numThang.TextAlign = HorizontalAlignment.Right;
            this.tabTKPage0.Controls.Add(this.numThang);
            this.label2 = new Label();
            this.label2.Name = "label2";
            this.label2.SetBounds(208,14,53,24);
            this.label2.Text = "Năm:";
            this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabTKPage0.Controls.Add(this.label2);
            this.numNam = new NumericUpDown();
            this.numNam.Name = "numNam";
            this.numNam.SetBounds(266,14,117,24);
            this.numNam.Minimum = 2000M;
            this.numNam.Maximum = 2100M;
            this.numNam.Value = 2026M;
            this.numNam.TextAlign = HorizontalAlignment.Right;
            this.tabTKPage0.Controls.Add(this.numNam);
            this.btnLuong = new Button();
            this.btnLuong.Name = "btnLuong";
            this.btnLuong.SetBounds(413,11,190,32);
            this.btnLuong.Text = "Tính lương";
            this.btnLuong.UseVisualStyleBackColor = false;
            this.btnLuong.FlatStyle = FlatStyle.Flat;
            this.btnLuong.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnLuong.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.tabTKPage0.Controls.Add(this.btnLuong);
            this.btnLuong.Click += btnLuong_Click;
            this.label3 = new Label();
            this.label3.Name = "label3";
            this.label3.SetBounds(632,14,616,24);
            this.label3.Text = "Lương = lương căn bản + thù lao các tour kết thúc trong tháng";
            this.label3.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.label3.ForeColor = System.Drawing.Color.Gray;
            this.tabTKPage0.Controls.Add(this.label3);
            this.dgvLuong = new DataGridView();
            this.dgvLuong.Name = "dgvLuong";
            this.dgvLuong.SetBounds(15,52,1243,370);
            this.dgvLuong.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            this.dgvLuong.BackgroundColor = System.Drawing.Color.White;
            this.dgvLuong.GridColor = System.Drawing.Color.FromArgb(220,220,220);
            this.dgvLuong.BorderStyle = BorderStyle.FixedSingle;
            this.dgvLuong.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
            this.dgvLuong.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvLuong.MultiSelect = false;
            this.dgvLuong.ReadOnly = true;
            this.dgvLuong.AllowUserToAddRows = false;
            this.dgvLuong.AllowUserToDeleteRows = false;
            this.dgvLuong.RowHeadersWidth = 30;
            this.dgvLuong.RowTemplate.Height = 25;
            this.dgvLuong.ColumnHeadersHeight = 25;
            this.dgvLuong.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.dgvLuong.EnableHeadersVisualStyles = false;
            this.dgvLuong.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.SystemColors.Control;
            this.dgvLuong.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(205,232,255);
            this.dgvLuong.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgvLuong.DefaultCellStyle.NullValue = "";
            this.dgvLuong.DefaultCellStyle.Format = "";
            this.tabTKPage0.Controls.Add(this.dgvLuong);
            this.dgvLuong.DataBindingComplete += FormHelper.DinhDangBang;
            this.dgvLuong.SizeChanged += FormHelper.KichThuocBangThayDoi;
            this.dgvLuong.CellValueChanged += FormHelper.DuLieuOThayDoi;
            this.label4 = new Label();
            this.label4.Name = "label4";
            this.label4.SetBounds(18,14,89,24);
            this.label4.Text = "Từ ngày:";
            this.label4.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabTKPage1.Controls.Add(this.label4);
            this.dtTu = new DateTimePicker();
            this.dtTu.Name = "dtTu";
            this.dtTu.SetBounds(113,14,190,24);
            this.dtTu.Format = DateTimePickerFormat.Custom;
            this.dtTu.CustomFormat = "dd/MM/yyyy";
            this.tabTKPage1.Controls.Add(this.dtTu);
            this.label5 = new Label();
            this.label5.Name = "label5";
            this.label5.SetBounds(332,14,89,24);
            this.label5.Text = "Đến ngày:";
            this.label5.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabTKPage1.Controls.Add(this.label5);
            this.dtDen = new DateTimePicker();
            this.dtDen.Name = "dtDen";
            this.dtDen.SetBounds(427,14,190,24);
            this.dtDen.Format = DateTimePickerFormat.Custom;
            this.dtDen.CustomFormat = "dd/MM/yyyy";
            this.tabTKPage1.Controls.Add(this.dtDen);
            this.btnTongHop = new Button();
            this.btnTongHop.Name = "btnTongHop";
            this.btnTongHop.SetBounds(647,11,190,32);
            this.btnTongHop.Text = "Thống kê";
            this.btnTongHop.UseVisualStyleBackColor = false;
            this.btnTongHop.FlatStyle = FlatStyle.Flat;
            this.btnTongHop.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnTongHop.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.tabTKPage1.Controls.Add(this.btnTongHop);
            this.btnTongHop.Click += btnTongHop_Click;
            this.dgvTongHop = new DataGridView();
            this.dgvTongHop.Name = "dgvTongHop";
            this.dgvTongHop.SetBounds(15,52,1243,370);
            this.dgvTongHop.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            this.dgvTongHop.BackgroundColor = System.Drawing.Color.White;
            this.dgvTongHop.GridColor = System.Drawing.Color.FromArgb(220,220,220);
            this.dgvTongHop.BorderStyle = BorderStyle.FixedSingle;
            this.dgvTongHop.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
            this.dgvTongHop.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvTongHop.MultiSelect = false;
            this.dgvTongHop.ReadOnly = true;
            this.dgvTongHop.AllowUserToAddRows = false;
            this.dgvTongHop.AllowUserToDeleteRows = false;
            this.dgvTongHop.RowHeadersWidth = 30;
            this.dgvTongHop.RowTemplate.Height = 25;
            this.dgvTongHop.ColumnHeadersHeight = 25;
            this.dgvTongHop.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.dgvTongHop.EnableHeadersVisualStyles = false;
            this.dgvTongHop.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.SystemColors.Control;
            this.dgvTongHop.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(205,232,255);
            this.dgvTongHop.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgvTongHop.DefaultCellStyle.NullValue = "";
            this.dgvTongHop.DefaultCellStyle.Format = "";
            this.tabTKPage1.Controls.Add(this.dgvTongHop);
            this.dgvTongHop.DataBindingComplete += FormHelper.DinhDangBang;
            this.dgvTongHop.SizeChanged += FormHelper.KichThuocBangThayDoi;
            this.dgvTongHop.CellValueChanged += FormHelper.DuLieuOThayDoi;
            this.btnDong = new Button();
            this.btnDong.Name = "btnDong";
            this.btnDong.SetBounds(1164,505,146,30);
            this.btnDong.Text = "Đóng";
            this.btnDong.UseVisualStyleBackColor = false;
            this.btnDong.FlatStyle = FlatStyle.Flat;
            this.btnDong.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnDong.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.Controls.Add(this.btnDong);
            this.btnDong.Click += btnDong_Click;
            this.btnDong.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            this.Load += FrmLuongThongKe_Load;
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
