using System;
using System.Windows.Forms;

namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmMain
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing) { if (disposing && components != null) components.Dispose(); base.Dispose(disposing); }
        private Label lblTieuDe;
        private Button btnDanhMuc;
        private Button btnTour;
        private Button btnChuyenLe;
        private Button btnDangKyLe;
        private Button btnDangKyDoan;
        private Button btnPhanCong;
        private Button btnKetThuc;
        private Button btnThongKe;
        private Button btnThoat;
        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F,96F);
            this.AutoScaleMode = AutoScaleMode.Dpi;
            this.ClientSize = new System.Drawing.Size(656,478);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Text = "Quản lý công ty du lịch Văn Hóa Việt";
            this.Name = "FrmMain";
            this.StartPosition = FormStartPosition.CenterParent;
            this.BackColor = System.Drawing.SystemColors.Control;
            this.MinimumSize = new System.Drawing.Size(672,517);
            this.lblTieuDe = new Label();
            this.lblTieuDe.Name = "lblTieuDe";
            this.lblTieuDe.SetBounds(45,20,566,42);
            this.lblTieuDe.Text = "CÔNG TY DU LỊCH VĂN HÓA VIỆT";
            this.lblTieuDe.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblTieuDe.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.Controls.Add(this.lblTieuDe);
            this.lblTieuDe.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblTieuDe.ForeColor = System.Drawing.Color.FromArgb(0,51,102);
            this.lblTieuDe.Font = new System.Drawing.Font("Segoe UI", 17F, System.Drawing.FontStyle.Bold);
            this.btnDanhMuc = new Button();
            this.btnDanhMuc.Name = "btnDanhMuc";
            this.btnDanhMuc.SetBounds(58,78,260,52);
            this.btnDanhMuc.Text = "Danh mục";
            this.btnDanhMuc.UseVisualStyleBackColor = false;
            this.btnDanhMuc.FlatStyle = FlatStyle.Flat;
            this.btnDanhMuc.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnDanhMuc.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.Controls.Add(this.btnDanhMuc);
            this.btnDanhMuc.Click += btnDanhMuc_Click;
            this.btnTour = new Button();
            this.btnTour.Name = "btnTour";
            this.btnTour.SetBounds(338,78,260,52);
            this.btnTour.Text = "Tour - hành trình";
            this.btnTour.UseVisualStyleBackColor = false;
            this.btnTour.FlatStyle = FlatStyle.Flat;
            this.btnTour.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnTour.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.Controls.Add(this.btnTour);
            this.btnTour.Click += btnTour_Click;
            this.btnChuyenLe = new Button();
            this.btnChuyenLe.Name = "btnChuyenLe";
            this.btnChuyenLe.SetBounds(58,148,260,52);
            this.btnChuyenLe.Text = "Lịch chuyến khách lẻ";
            this.btnChuyenLe.UseVisualStyleBackColor = false;
            this.btnChuyenLe.FlatStyle = FlatStyle.Flat;
            this.btnChuyenLe.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnChuyenLe.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.Controls.Add(this.btnChuyenLe);
            this.btnChuyenLe.Click += btnChuyenLe_Click;
            this.btnDangKyLe = new Button();
            this.btnDangKyLe.Name = "btnDangKyLe";
            this.btnDangKyLe.SetBounds(338,148,260,52);
            this.btnDangKyLe.Text = "Đăng ký khách lẻ";
            this.btnDangKyLe.UseVisualStyleBackColor = false;
            this.btnDangKyLe.FlatStyle = FlatStyle.Flat;
            this.btnDangKyLe.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnDangKyLe.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.Controls.Add(this.btnDangKyLe);
            this.btnDangKyLe.Click += btnDangKyLe_Click;
            this.btnDangKyDoan = new Button();
            this.btnDangKyDoan.Name = "btnDangKyDoan";
            this.btnDangKyDoan.SetBounds(58,218,260,52);
            this.btnDangKyDoan.Text = "Đăng ký theo đoàn";
            this.btnDangKyDoan.UseVisualStyleBackColor = false;
            this.btnDangKyDoan.FlatStyle = FlatStyle.Flat;
            this.btnDangKyDoan.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnDangKyDoan.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.Controls.Add(this.btnDangKyDoan);
            this.btnDangKyDoan.Click += btnDangKyDoan_Click;
            this.btnPhanCong = new Button();
            this.btnPhanCong.Name = "btnPhanCong";
            this.btnPhanCong.SetBounds(338,218,260,52);
            this.btnPhanCong.Text = "Phân công hướng dẫn viên";
            this.btnPhanCong.UseVisualStyleBackColor = false;
            this.btnPhanCong.FlatStyle = FlatStyle.Flat;
            this.btnPhanCong.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnPhanCong.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.Controls.Add(this.btnPhanCong);
            this.btnPhanCong.Click += btnPhanCong_Click;
            this.btnKetThuc = new Button();
            this.btnKetThuc.Name = "btnKetThuc";
            this.btnKetThuc.SetBounds(58,288,260,52);
            this.btnKetThuc.Text = "Kết thúc tour - khảo sát";
            this.btnKetThuc.UseVisualStyleBackColor = false;
            this.btnKetThuc.FlatStyle = FlatStyle.Flat;
            this.btnKetThuc.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnKetThuc.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.Controls.Add(this.btnKetThuc);
            this.btnKetThuc.Click += btnKetThuc_Click;
            this.btnThongKe = new Button();
            this.btnThongKe.Name = "btnThongKe";
            this.btnThongKe.SetBounds(338,288,260,52);
            this.btnThongKe.Text = "Lương - thống kê";
            this.btnThongKe.UseVisualStyleBackColor = false;
            this.btnThongKe.FlatStyle = FlatStyle.Flat;
            this.btnThongKe.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnThongKe.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.Controls.Add(this.btnThongKe);
            this.btnThongKe.Click += btnThongKe_Click;
            this.btnThoat = new Button();
            this.btnThoat.Name = "btnThoat";
            this.btnThoat.SetBounds(198,368,260,52);
            this.btnThoat.Text = "Thoát";
            this.btnThoat.UseVisualStyleBackColor = false;
            this.btnThoat.FlatStyle = FlatStyle.Flat;
            this.btnThoat.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnThoat.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.Controls.Add(this.btnThoat);
            this.btnThoat.Click += btnThoat_Click;
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
