using System;
using System.Windows.Forms;

namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmPhanCongHDV
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing) { if (disposing && components != null) components.Dispose(); base.Dispose(disposing); }
        private Label label1;
        private TextBox txtMaPC;
        private Label label2;
        private ComboBox cboHDV;
        private Label label3;
        private ComboBox cboLoai;
        private Label label4;
        private ComboBox cboDoiTuong;
        private Label label5;
        private NumericUpDown numThuLao;
        private Label label6;
        private Button btnPhanCong;
        private DataGridView dgv;
        private Button btnDong;
        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F,96F);
            this.AutoScaleMode = AutoScaleMode.Dpi;
            this.ClientSize = new System.Drawing.Size(1340,528);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Text = "Phân công hướng dẫn viên";
            this.Name = "FrmPhanCongHDV";
            this.StartPosition = FormStartPosition.CenterParent;
            this.BackColor = System.Drawing.SystemColors.Control;
            this.MinimumSize = new System.Drawing.Size(1356,567);
            this.label1 = new Label();
            this.label1.Name = "label1";
            this.label1.SetBounds(32,18,139,24);
            this.label1.Text = "Mã phân công:";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.label1);
            this.txtMaPC = new TextBox();
            this.txtMaPC.Name = "txtMaPC";
            this.txtMaPC.SetBounds(171,18,176,24);
            this.txtMaPC.MaxLength = 1000;
            this.Controls.Add(this.txtMaPC);
            this.label2 = new Label();
            this.label2.Name = "label2";
            this.label2.SetBounds(391,18,146,24);
            this.label2.Text = "Hướng dẫn viên:";
            this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.label2);
            this.cboHDV = new ComboBox();
            this.cboHDV.Name = "cboHDV";
            this.cboHDV.SetBounds(537,18,366,24);
            this.cboHDV.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboHDV.DropDownWidth = 600;
            this.Controls.Add(this.cboHDV);
            this.label3 = new Label();
            this.label3.Name = "label3";
            this.label3.SetBounds(32,53,139,24);
            this.label3.Text = "Loại:";
            this.label3.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.label3);
            this.cboLoai = new ComboBox();
            this.cboLoai.Name = "cboLoai";
            this.cboLoai.SetBounds(171,53,176,24);
            this.cboLoai.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboLoai.DropDownWidth = 600;
            this.Controls.Add(this.cboLoai);
            this.cboLoai.SelectedIndexChanged += cboLoai_SelectedIndexChanged;
            this.label4 = new Label();
            this.label4.Name = "label4";
            this.label4.SetBounds(391,53,146,24);
            this.label4.Text = "Chuyến / đoàn:";
            this.label4.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.label4);
            this.cboDoiTuong = new ComboBox();
            this.cboDoiTuong.Name = "cboDoiTuong";
            this.cboDoiTuong.SetBounds(537,53,556,24);
            this.cboDoiTuong.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboDoiTuong.DropDownWidth = 600;
            this.Controls.Add(this.cboDoiTuong);
            this.label5 = new Label();
            this.label5.Name = "label5";
            this.label5.SetBounds(32,88,139,24);
            this.label5.Text = "Thù lao tour:";
            this.label5.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.label5);
            this.numThuLao = new NumericUpDown();
            this.numThuLao.Name = "numThuLao";
            this.numThuLao.SetBounds(171,88,219,24);
            this.numThuLao.Minimum = 0M;
            this.numThuLao.Maximum = 1000000000M;
            this.numThuLao.Value = 1500000M;
            this.numThuLao.TextAlign = HorizontalAlignment.Right;
            this.numThuLao.ThousandsSeparator = true;
            this.numThuLao.Increment = 100000M;
            this.Controls.Add(this.numThuLao);
            this.label6 = new Label();
            this.label6.Name = "label6";
            this.label6.SetBounds(420,88,673,24);
            this.label6.Text = "Ngày bắt đầu / kết thúc lấy theo chuyến hoặc phiếu đoàn.";
            this.label6.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.label6.ForeColor = System.Drawing.Color.Gray;
            this.Controls.Add(this.label6);
            this.btnPhanCong = new Button();
            this.btnPhanCong.Name = "btnPhanCong";
            this.btnPhanCong.SetBounds(1093,85,212,34);
            this.btnPhanCong.Text = "Phân công";
            this.btnPhanCong.UseVisualStyleBackColor = false;
            this.btnPhanCong.FlatStyle = FlatStyle.Flat;
            this.btnPhanCong.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnPhanCong.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.Controls.Add(this.btnPhanCong);
            this.btnPhanCong.Click += btnPhanCong_Click;
            this.dgv = new DataGridView();
            this.dgv.Name = "dgv";
            this.dgv.SetBounds(32,133,1273,340);
            this.dgv.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            this.dgv.BackgroundColor = System.Drawing.Color.White;
            this.dgv.GridColor = System.Drawing.Color.FromArgb(220,220,220);
            this.dgv.BorderStyle = BorderStyle.FixedSingle;
            this.dgv.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
            this.dgv.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgv.MultiSelect = false;
            this.dgv.ReadOnly = true;
            this.dgv.AllowUserToAddRows = false;
            this.dgv.AllowUserToDeleteRows = false;
            this.dgv.RowHeadersWidth = 30;
            this.dgv.RowTemplate.Height = 25;
            this.dgv.ColumnHeadersHeight = 25;
            this.dgv.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.dgv.EnableHeadersVisualStyles = false;
            this.dgv.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.SystemColors.Control;
            this.dgv.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(205,232,255);
            this.dgv.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgv.DefaultCellStyle.NullValue = "";
            this.dgv.DefaultCellStyle.Format = "";
            this.Controls.Add(this.dgv);
            this.dgv.DataBindingComplete += FormHelper.DinhDangBang;
            this.dgv.SizeChanged += FormHelper.KichThuocBangThayDoi;
            this.dgv.CellValueChanged += FormHelper.DuLieuOThayDoi;
            this.btnDong = new Button();
            this.btnDong.Name = "btnDong";
            this.btnDong.SetBounds(1164,485,146,30);
            this.btnDong.Text = "Đóng";
            this.btnDong.UseVisualStyleBackColor = false;
            this.btnDong.FlatStyle = FlatStyle.Flat;
            this.btnDong.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnDong.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.Controls.Add(this.btnDong);
            this.btnDong.Click += btnDong_Click;
            this.btnDong.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            this.Load += FrmPhanCongHDV_Load;
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
