using System;
using System.Windows.Forms;

namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmTour
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing) { if (disposing && components != null) components.Dispose(); base.Dispose(disposing); }
        private Label label1;
        private ComboBox cboTour;
        private TabControl tabTour;
        private TabPage tabTourPage0;
        private TabPage tabTourPage1;
        private TabPage tabTourPage2;
        private TabPage tabTourPage3;
        private DataGridView dgvTour;
        private DataGridView dgvDiemDung;
        private DataGridView dgvChang;
        private DataGridView dgvTQ;
        private Label label2;
        private TextBox txtMa;
        private Label label3;
        private TextBox txtTen;
        private Label label4;
        private TextBox txtMoTa;
        private Label label5;
        private NumericUpDown numNgay;
        private Label label6;
        private NumericUpDown numDem;
        private Label label7;
        private NumericUpDown numGia;
        private Button btnThemTour;
        private Label label8;
        private NumericUpDown numThuTu;
        private Label label9;
        private TextBox txtDiemDung;
        private CheckBox chkDoiPT;
        private CheckBox chkAn;
        private CheckBox chkKS;
        private Label label10;
        private NumericUpDown numSao;
        private Label label11;
        private TextBox txtGhiChuDD;
        private Button btnThemDD;
        private Label label12;
        private NumericUpDown numChang;
        private Label label13;
        private ComboBox cboPT;
        private Label label14;
        private TextBox txtGhiChuPT;
        private Button btnThemChang;
        private Label label15;
        private Label label16;
        private ComboBox cboDTQ;
        private Label label17;
        private NumericUpDown numThuTuTQ;
        private Button btnThemTQ;
        private Button btnDong;
        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F,96F);
            this.AutoScaleMode = AutoScaleMode.Dpi;
            this.ClientSize = new System.Drawing.Size(1340,608);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Text = "Tour - hành trình";
            this.Name = "FrmTour";
            this.StartPosition = FormStartPosition.CenterParent;
            this.BackColor = System.Drawing.SystemColors.Control;
            this.MinimumSize = new System.Drawing.Size(1356,647);
            this.label1 = new Label();
            this.label1.Name = "label1";
            this.label1.SetBounds(29,18,323,24);
            this.label1.Text = "Tour đang chọn (cho các tab hành trình):";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.label1);
            this.cboTour = new ComboBox();
            this.cboTour.Name = "cboTour";
            this.cboTour.SetBounds(359,18,396,24);
            this.cboTour.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboTour.DropDownWidth = 600;
            this.Controls.Add(this.cboTour);
            this.cboTour.SelectedIndexChanged += cboTour_SelectedIndexChanged;
            this.tabTour = new TabControl();
            this.tabTour.Name = "tabTour";
            this.tabTour.SetBounds(26,54,1287,505);
            this.tabTour.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            this.Controls.Add(this.tabTour);
            this.tabTourPage0 = new TabPage();
            this.tabTourPage0.Name = "tabTourPage0";
            this.tabTourPage0.SetBounds(0,0,1277,480);
            this.tabTourPage0.Text = "Tour";
            this.tabTourPage0.BackColor = System.Drawing.Color.White;
            this.tabTour.Controls.Add(this.tabTourPage0);
            this.tabTourPage1 = new TabPage();
            this.tabTourPage1.Name = "tabTourPage1";
            this.tabTourPage1.SetBounds(0,0,1277,480);
            this.tabTourPage1.Text = "Điểm dừng";
            this.tabTourPage1.BackColor = System.Drawing.Color.White;
            this.tabTour.Controls.Add(this.tabTourPage1);
            this.tabTourPage2 = new TabPage();
            this.tabTourPage2.Name = "tabTourPage2";
            this.tabTourPage2.SetBounds(0,0,1277,480);
            this.tabTourPage2.Text = "Phương tiện theo chặng";
            this.tabTourPage2.BackColor = System.Drawing.Color.White;
            this.tabTour.Controls.Add(this.tabTourPage2);
            this.tabTourPage3 = new TabPage();
            this.tabTourPage3.Name = "tabTourPage3";
            this.tabTourPage3.SetBounds(0,0,1277,480);
            this.tabTourPage3.Text = "Điểm tham quan";
            this.tabTourPage3.BackColor = System.Drawing.Color.White;
            this.tabTour.Controls.Add(this.tabTourPage3);
            this.dgvTour = new DataGridView();
            this.dgvTour.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            this.dgvTour.Name = "dgvTour";
            this.dgvTour.SetBounds(13,10,1253,300);
            this.dgvTour.BackgroundColor = System.Drawing.Color.White;
            this.dgvTour.GridColor = System.Drawing.Color.FromArgb(220,220,220);
            this.dgvTour.BorderStyle = BorderStyle.FixedSingle;
            this.dgvTour.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
            this.dgvTour.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvTour.MultiSelect = false;
            this.dgvTour.ReadOnly = true;
            this.dgvTour.AllowUserToAddRows = false;
            this.dgvTour.AllowUserToDeleteRows = false;
            this.dgvTour.RowHeadersWidth = 30;
            this.dgvTour.RowTemplate.Height = 25;
            this.dgvTour.ColumnHeadersHeight = 25;
            this.dgvTour.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.dgvTour.EnableHeadersVisualStyles = false;
            this.dgvTour.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.SystemColors.Control;
            this.dgvTour.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(205,232,255);
            this.dgvTour.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgvTour.DefaultCellStyle.NullValue = "";
            this.dgvTour.DefaultCellStyle.Format = "";
            this.tabTourPage0.Controls.Add(this.dgvTour);
            this.dgvTour.DataBindingComplete += FormHelper.DinhDangBang;
            this.dgvTour.SizeChanged += FormHelper.KichThuocBangThayDoi;
            this.dgvTour.CellValueChanged += FormHelper.DuLieuOThayDoi;
            this.dgvDiemDung = new DataGridView();
            this.dgvDiemDung.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            this.dgvDiemDung.Name = "dgvDiemDung";
            this.dgvDiemDung.SetBounds(13,10,1253,300);
            this.dgvDiemDung.BackgroundColor = System.Drawing.Color.White;
            this.dgvDiemDung.GridColor = System.Drawing.Color.FromArgb(220,220,220);
            this.dgvDiemDung.BorderStyle = BorderStyle.FixedSingle;
            this.dgvDiemDung.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
            this.dgvDiemDung.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvDiemDung.MultiSelect = false;
            this.dgvDiemDung.ReadOnly = true;
            this.dgvDiemDung.AllowUserToAddRows = false;
            this.dgvDiemDung.AllowUserToDeleteRows = false;
            this.dgvDiemDung.RowHeadersWidth = 30;
            this.dgvDiemDung.RowTemplate.Height = 25;
            this.dgvDiemDung.ColumnHeadersHeight = 25;
            this.dgvDiemDung.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.dgvDiemDung.EnableHeadersVisualStyles = false;
            this.dgvDiemDung.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.SystemColors.Control;
            this.dgvDiemDung.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(205,232,255);
            this.dgvDiemDung.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgvDiemDung.DefaultCellStyle.NullValue = "";
            this.dgvDiemDung.DefaultCellStyle.Format = "";
            this.tabTourPage1.Controls.Add(this.dgvDiemDung);
            this.dgvDiemDung.DataBindingComplete += FormHelper.DinhDangBang;
            this.dgvDiemDung.SizeChanged += FormHelper.KichThuocBangThayDoi;
            this.dgvDiemDung.CellValueChanged += FormHelper.DuLieuOThayDoi;
            this.dgvChang = new DataGridView();
            this.dgvChang.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            this.dgvChang.Name = "dgvChang";
            this.dgvChang.SetBounds(13,10,1253,300);
            this.dgvChang.BackgroundColor = System.Drawing.Color.White;
            this.dgvChang.GridColor = System.Drawing.Color.FromArgb(220,220,220);
            this.dgvChang.BorderStyle = BorderStyle.FixedSingle;
            this.dgvChang.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
            this.dgvChang.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvChang.MultiSelect = false;
            this.dgvChang.ReadOnly = true;
            this.dgvChang.AllowUserToAddRows = false;
            this.dgvChang.AllowUserToDeleteRows = false;
            this.dgvChang.RowHeadersWidth = 30;
            this.dgvChang.RowTemplate.Height = 25;
            this.dgvChang.ColumnHeadersHeight = 25;
            this.dgvChang.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.dgvChang.EnableHeadersVisualStyles = false;
            this.dgvChang.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.SystemColors.Control;
            this.dgvChang.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(205,232,255);
            this.dgvChang.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgvChang.DefaultCellStyle.NullValue = "";
            this.dgvChang.DefaultCellStyle.Format = "";
            this.tabTourPage2.Controls.Add(this.dgvChang);
            this.dgvChang.DataBindingComplete += FormHelper.DinhDangBang;
            this.dgvChang.SizeChanged += FormHelper.KichThuocBangThayDoi;
            this.dgvChang.CellValueChanged += FormHelper.DuLieuOThayDoi;
            this.dgvTQ = new DataGridView();
            this.dgvTQ.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            this.dgvTQ.Name = "dgvTQ";
            this.dgvTQ.SetBounds(13,10,1253,300);
            this.dgvTQ.BackgroundColor = System.Drawing.Color.White;
            this.dgvTQ.GridColor = System.Drawing.Color.FromArgb(220,220,220);
            this.dgvTQ.BorderStyle = BorderStyle.FixedSingle;
            this.dgvTQ.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
            this.dgvTQ.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvTQ.MultiSelect = false;
            this.dgvTQ.ReadOnly = true;
            this.dgvTQ.AllowUserToAddRows = false;
            this.dgvTQ.AllowUserToDeleteRows = false;
            this.dgvTQ.RowHeadersWidth = 30;
            this.dgvTQ.RowTemplate.Height = 25;
            this.dgvTQ.ColumnHeadersHeight = 25;
            this.dgvTQ.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.dgvTQ.EnableHeadersVisualStyles = false;
            this.dgvTQ.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.SystemColors.Control;
            this.dgvTQ.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(205,232,255);
            this.dgvTQ.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgvTQ.DefaultCellStyle.NullValue = "";
            this.dgvTQ.DefaultCellStyle.Format = "";
            this.tabTourPage3.Controls.Add(this.dgvTQ);
            this.dgvTQ.DataBindingComplete += FormHelper.DinhDangBang;
            this.dgvTQ.SizeChanged += FormHelper.KichThuocBangThayDoi;
            this.dgvTQ.CellValueChanged += FormHelper.DuLieuOThayDoi;
            this.label2 = new Label();
            this.label2.Name = "label2";
            this.label2.SetBounds(16,329,106,24);
            this.label2.Text = "Mã tour:";
            this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabTourPage0.Controls.Add(this.label2);
            this.txtMa = new TextBox();
            this.txtMa.Name = "txtMa";
            this.txtMa.SetBounds(121,329,171,24);
            this.txtMa.MaxLength = 1000;
            this.tabTourPage0.Controls.Add(this.txtMa);
            this.label3 = new Label();
            this.label3.Name = "label3";
            this.label3.SetBounds(319,329,106,24);
            this.label3.Text = "Tên tour:";
            this.label3.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabTourPage0.Controls.Add(this.label3);
            this.txtTen = new TextBox();
            this.txtTen.Name = "txtTen";
            this.txtTen.SetBounds(425,329,501,24);
            this.txtTen.MaxLength = 1000;
            this.tabTourPage0.Controls.Add(this.txtTen);
            this.label4 = new Label();
            this.label4.Name = "label4";
            this.label4.SetBounds(16,399,106,24);
            this.label4.Text = "Mô tả:";
            this.label4.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabTourPage0.Controls.Add(this.label4);
            this.txtMoTa = new TextBox();
            this.txtMoTa.Name = "txtMoTa";
            this.txtMoTa.SetBounds(121,399,857,24);
            this.txtMoTa.MaxLength = 1000;
            this.tabTourPage0.Controls.Add(this.txtMoTa);
            this.label5 = new Label();
            this.label5.Name = "label5";
            this.label5.SetBounds(16,364,106,24);
            this.label5.Text = "Số ngày:";
            this.label5.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabTourPage0.Controls.Add(this.label5);
            this.numNgay = new NumericUpDown();
            this.numNgay.Name = "numNgay";
            this.numNgay.SetBounds(121,364,106,24);
            this.numNgay.Minimum = 1M;
            this.numNgay.Maximum = 365M;
            this.numNgay.Value = 3M;
            this.numNgay.TextAlign = HorizontalAlignment.Right;
            this.tabTourPage0.Controls.Add(this.numNgay);
            this.label6 = new Label();
            this.label6.Name = "label6";
            this.label6.SetBounds(319,364,92,24);
            this.label6.Text = "Số đêm:";
            this.label6.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabTourPage0.Controls.Add(this.label6);
            this.numDem = new NumericUpDown();
            this.numDem.Name = "numDem";
            this.numDem.SetBounds(411,364,106,24);
            this.numDem.Minimum = 0M;
            this.numDem.Maximum = 365M;
            this.numDem.Value = 2M;
            this.numDem.TextAlign = HorizontalAlignment.Right;
            this.tabTourPage0.Controls.Add(this.numDem);
            this.label7 = new Label();
            this.label7.Name = "label7";
            this.label7.SetBounds(557,364,145,24);
            this.label7.Text = "Đơn giá / khách:";
            this.label7.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabTourPage0.Controls.Add(this.label7);
            this.numGia = new NumericUpDown();
            this.numGia.Name = "numGia";
            this.numGia.SetBounds(702,364,198,24);
            this.numGia.Minimum = 0M;
            this.numGia.Maximum = 1000000000M;
            this.numGia.Value = 2500000M;
            this.numGia.TextAlign = HorizontalAlignment.Right;
            this.numGia.ThousandsSeparator = true;
            this.numGia.Increment = 100000M;
            this.tabTourPage0.Controls.Add(this.numGia);
            this.btnThemTour = new Button();
            this.btnThemTour.Name = "btnThemTour";
            this.btnThemTour.SetBounds(1095,396,158,32);
            this.btnThemTour.Text = "Thêm tour";
            this.btnThemTour.UseVisualStyleBackColor = false;
            this.btnThemTour.FlatStyle = FlatStyle.Flat;
            this.btnThemTour.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnThemTour.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.tabTourPage0.Controls.Add(this.btnThemTour);
            this.btnThemTour.Click += btnThemTour_Click;
            this.label8 = new Label();
            this.label8.Name = "label8";
            this.label8.SetBounds(16,329,92,24);
            this.label8.Text = "Thứ tự:";
            this.label8.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabTourPage1.Controls.Add(this.label8);
            this.numThuTu = new NumericUpDown();
            this.numThuTu.Name = "numThuTu";
            this.numThuTu.SetBounds(108,329,92,24);
            this.numThuTu.Minimum = 1M;
            this.numThuTu.Maximum = 1000M;
            this.numThuTu.Value = 1M;
            this.numThuTu.TextAlign = HorizontalAlignment.Right;
            this.tabTourPage1.Controls.Add(this.numThuTu);
            this.label9 = new Label();
            this.label9.Name = "label9";
            this.label9.SetBounds(227,329,132,24);
            this.label9.Text = "Tên điểm dừng:";
            this.label9.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabTourPage1.Controls.Add(this.label9);
            this.txtDiemDung = new TextBox();
            this.txtDiemDung.Name = "txtDiemDung";
            this.txtDiemDung.SetBounds(359,329,330,24);
            this.txtDiemDung.MaxLength = 1000;
            this.tabTourPage1.Controls.Add(this.txtDiemDung);
            this.chkDoiPT = new CheckBox();
            this.chkDoiPT.Name = "chkDoiPT";
            this.chkDoiPT.SetBounds(16,364,185,25);
            this.chkDoiPT.Text = "Đổi phương tiện";
            this.tabTourPage1.Controls.Add(this.chkDoiPT);
            this.chkAn = new CheckBox();
            this.chkAn.Name = "chkAn";
            this.chkAn.SetBounds(214,364,152,25);
            this.chkAn.Text = "Có nơi ăn";
            this.tabTourPage1.Controls.Add(this.chkAn);
            this.chkKS = new CheckBox();
            this.chkKS.Name = "chkKS";
            this.chkKS.SetBounds(372,364,171,25);
            this.chkKS.Text = "Có khách sạn";
            this.tabTourPage1.Controls.Add(this.chkKS);
            this.chkKS.CheckedChanged += chkKS_CheckedChanged;
            this.label10 = new Label();
            this.label10.Name = "label10";
            this.label10.SetBounds(557,364,86,24);
            this.label10.Text = "Hạng sao:";
            this.label10.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabTourPage1.Controls.Add(this.label10);
            this.numSao = new NumericUpDown();
            this.numSao.Name = "numSao";
            this.numSao.SetBounds(642,364,79,24);
            this.numSao.Minimum = 2M;
            this.numSao.Maximum = 5M;
            this.numSao.Value = 3M;
            this.numSao.TextAlign = HorizontalAlignment.Right;
            this.tabTourPage1.Controls.Add(this.numSao);
            this.numSao.Enabled = false;
            this.label11 = new Label();
            this.label11.Name = "label11";
            this.label11.SetBounds(16,399,92,24);
            this.label11.Text = "Ghi chú:";
            this.label11.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabTourPage1.Controls.Add(this.label11);
            this.txtGhiChuDD = new TextBox();
            this.txtGhiChuDD.Name = "txtGhiChuDD";
            this.txtGhiChuDD.SetBounds(108,399,791,24);
            this.txtGhiChuDD.MaxLength = 1000;
            this.tabTourPage1.Controls.Add(this.txtGhiChuDD);
            this.btnThemDD = new Button();
            this.btnThemDD.Name = "btnThemDD";
            this.btnThemDD.SetBounds(1095,396,158,32);
            this.btnThemDD.Text = "Thêm điểm dừng";
            this.btnThemDD.UseVisualStyleBackColor = false;
            this.btnThemDD.FlatStyle = FlatStyle.Flat;
            this.btnThemDD.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnThemDD.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.tabTourPage1.Controls.Add(this.btnThemDD);
            this.btnThemDD.Click += btnThemDD_Click;
            this.label12 = new Label();
            this.label12.Name = "label12";
            this.label12.SetBounds(16,329,99,24);
            this.label12.Text = "Chặng thứ:";
            this.label12.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabTourPage2.Controls.Add(this.label12);
            this.numChang = new NumericUpDown();
            this.numChang.Name = "numChang";
            this.numChang.SetBounds(115,329,92,24);
            this.numChang.Minimum = 1M;
            this.numChang.Maximum = 1000M;
            this.numChang.Value = 1M;
            this.numChang.TextAlign = HorizontalAlignment.Right;
            this.tabTourPage2.Controls.Add(this.numChang);
            this.label13 = new Label();
            this.label13.Name = "label13";
            this.label13.SetBounds(240,329,112,24);
            this.label13.Text = "Phương tiện:";
            this.label13.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabTourPage2.Controls.Add(this.label13);
            this.cboPT = new ComboBox();
            this.cboPT.Name = "cboPT";
            this.cboPT.SetBounds(352,329,264,24);
            this.cboPT.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboPT.DropDownWidth = 600;
            this.tabTourPage2.Controls.Add(this.cboPT);
            this.label14 = new Label();
            this.label14.Name = "label14";
            this.label14.SetBounds(16,364,99,24);
            this.label14.Text = "Ghi chú:";
            this.label14.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabTourPage2.Controls.Add(this.label14);
            this.txtGhiChuPT = new TextBox();
            this.txtGhiChuPT.Name = "txtGhiChuPT";
            this.txtGhiChuPT.SetBounds(115,364,791,24);
            this.txtGhiChuPT.MaxLength = 1000;
            this.tabTourPage2.Controls.Add(this.txtGhiChuPT);
            this.btnThemChang = new Button();
            this.btnThemChang.Name = "btnThemChang";
            this.btnThemChang.SetBounds(1095,361,158,32);
            this.btnThemChang.Text = "Gắn phương tiện";
            this.btnThemChang.UseVisualStyleBackColor = false;
            this.btnThemChang.FlatStyle = FlatStyle.Flat;
            this.btnThemChang.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnThemChang.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.tabTourPage2.Controls.Add(this.btnThemChang);
            this.btnThemChang.Click += btnThemChang_Click;
            this.label15 = new Label();
            this.label15.Name = "label15";
            this.label15.SetBounds(16,399,1002,24);
            this.label15.Text = "Chặng k là đoạn đi tới điểm dừng thứ k; một chặng có thể dùng nhiều phương tiện.";
            this.label15.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.label15.ForeColor = System.Drawing.Color.Gray;
            this.tabTourPage2.Controls.Add(this.label15);
            this.label16 = new Label();
            this.label16.Name = "label16";
            this.label16.SetBounds(16,329,138,24);
            this.label16.Text = "Điểm tham quan:";
            this.label16.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabTourPage3.Controls.Add(this.label16);
            this.cboDTQ = new ComboBox();
            this.cboDTQ.Name = "cboDTQ";
            this.cboDTQ.SetBounds(154,329,330,24);
            this.cboDTQ.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboDTQ.DropDownWidth = 600;
            this.tabTourPage3.Controls.Add(this.cboDTQ);
            this.label17 = new Label();
            this.label17.Name = "label17";
            this.label17.SetBounds(517,329,79,24);
            this.label17.Text = "Thứ tự:";
            this.label17.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tabTourPage3.Controls.Add(this.label17);
            this.numThuTuTQ = new NumericUpDown();
            this.numThuTuTQ.Name = "numThuTuTQ";
            this.numThuTuTQ.SetBounds(596,329,92,24);
            this.numThuTuTQ.Minimum = 1M;
            this.numThuTuTQ.Maximum = 1000M;
            this.numThuTuTQ.Value = 1M;
            this.numThuTuTQ.TextAlign = HorizontalAlignment.Right;
            this.tabTourPage3.Controls.Add(this.numThuTuTQ);
            this.btnThemTQ = new Button();
            this.btnThemTQ.Name = "btnThemTQ";
            this.btnThemTQ.SetBounds(1095,326,158,32);
            this.btnThemTQ.Text = "Gắn điểm TQ";
            this.btnThemTQ.UseVisualStyleBackColor = false;
            this.btnThemTQ.FlatStyle = FlatStyle.Flat;
            this.btnThemTQ.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnThemTQ.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.tabTourPage3.Controls.Add(this.btnThemTQ);
            this.btnThemTQ.Click += btnThemTQ_Click;
            this.btnDong = new Button();
            this.btnDong.Name = "btnDong";
            this.btnDong.SetBounds(1182,565,132,30);
            this.btnDong.Text = "Đóng";
            this.btnDong.UseVisualStyleBackColor = false;
            this.btnDong.FlatStyle = FlatStyle.Flat;
            this.btnDong.BackColor = System.Drawing.Color.FromArgb(225,225,225);
            this.btnDong.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(169,169,169);
            this.Controls.Add(this.btnDong);
            this.btnDong.Click += btnDong_Click;
            this.btnDong.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            this.Load += FrmTour_Load;
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
